// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.Item.DocumentId.ShipperNumber
{
    /// <summary>
    /// Builds and executes requests for operations under \Paperless\paperlessdocuments\{version}\DocumentId\ShipperNumber
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShipperNumberRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.Item.DocumentId.ShipperNumber.ShipperNumberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShipperNumberRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Paperless/paperlessdocuments/{version}/DocumentId/ShipperNumber", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.Item.DocumentId.ShipperNumber.ShipperNumberRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShipperNumberRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Paperless/paperlessdocuments/{version}/DocumentId/ShipperNumber", rawUrl)
        {
        }
        /// <summary>
        /// The Paperless Document API web service allows the users to upload their own customized trade documents for customs clearance to Forms History.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.PaperlessPAPERLESSDOCUMENTDeleteResponseWrapper"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.PaperlessPAPERLESSDOCUMENTDeleteResponseWrapper?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.PaperlessPAPERLESSDOCUMENTDeleteResponseWrapper> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Ups.OpenApiClient.Models.PaperlessErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.PaperlessPAPERLESSDOCUMENTDeleteResponseWrapper>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.PaperlessPAPERLESSDOCUMENTDeleteResponseWrapper.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The Paperless Document API web service allows the users to upload their own customized trade documents for customs clearance to Forms History.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.Item.DocumentId.ShipperNumber.ShipperNumberRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.Item.DocumentId.ShipperNumber.ShipperNumberRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.Item.DocumentId.ShipperNumber.ShipperNumberRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
