// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.OAuthClientCredentialsReady.Security.V1.Oauth.Token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ups.OpenApiClient.OAuthClientCredentialsReady.Security.V1.Oauth
{
    /// <summary>
    /// Builds and executes requests for operations under \OAuthClientCredentials-Ready\security\v1\oauth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OauthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The token property</summary>
        public global::Soenneker.Ups.OpenApiClient.OAuthClientCredentialsReady.Security.V1.Oauth.Token.TokenRequestBuilder Token
        {
            get => new global::Soenneker.Ups.OpenApiClient.OAuthClientCredentialsReady.Security.V1.Oauth.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.OAuthClientCredentialsReady.Security.V1.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/OAuthClientCredentials-Ready/security/v1/oauth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.OAuthClientCredentialsReady.Security.V1.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/OAuthClientCredentials-Ready/security/v1/oauth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
