// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetLocation_id_category_codeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "01")]
        #pragma warning disable CS1591
        ZeroOne,
        #pragma warning restore CS1591
        [EnumMember(Value = "02")]
        #pragma warning disable CS1591
        ZeroTwo,
        #pragma warning restore CS1591
    }
}
