// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \UPSPickupPoints\sites\{startdate}\{enddate}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEnddateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnddateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UPSPickupPoints/sites/{startdate}/{enddate}{?city*,country*,limit*,location_id_category_code*,location_identifier*,offset*,sort*,state*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnddateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/UPSPickupPoints/sites/{startdate}/{enddate}{?city*,country*,limit*,location_id_category_code*,location_identifier*,offset*,sort*,state*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns site details for the provided date range.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns site details from a user&apos;s preferences for the provided date range.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse"/></returns>
        /// <param name="body">Request payload for retrieving site details filtered by location identifier category.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse?> PostAsync(global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsRequest body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse> PostAsync(global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsRequest body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.UPSPickupPointsErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns site details for the provided date range.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns site details from a user&apos;s preferences for the provided date range.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request payload for retrieving site details filtered by location identifier category.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsRequest body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.SiteDetailsRequest body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder.WithEnddateItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.WithEnddateItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns site details for the provided date range.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEnddateItemRequestBuilderGetQueryParameters 
        {
            /// <summary>City filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("city")]
            public string? City { get; set; }
#nullable restore
#else
            [QueryParameter("city")]
            public string City { get; set; }
#endif
            /// <summary>Country filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("country")]
            public string? Country { get; set; }
#nullable restore
#else
            [QueryParameter("country")]
            public string Country { get; set; }
#endif
            /// <summary>Maximum records per page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("limit")]
            public string? Limit { get; set; }
#nullable restore
#else
            [QueryParameter("limit")]
            public string Limit { get; set; }
#endif
            /// <summary>Location identifier category code filter.</summary>
            [QueryParameter("location_id_category_code")]
            public global::Soenneker.Ups.OpenApiClient.UPSPickupPoints.Sites.Item.Item.GetLocation_id_category_codeQueryParameterType? LocationIdCategoryCode { get; set; }
            /// <summary>Location identifier filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("location_identifier")]
            public string? LocationIdentifier { get; set; }
#nullable restore
#else
            [QueryParameter("location_identifier")]
            public string LocationIdentifier { get; set; }
#endif
            /// <summary>Record offset for pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>Sort expression.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>State filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
        }
        /// <summary>
        /// Returns site details from a user&apos;s preferences for the provided date range.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithEnddateItemRequestBuilderPostQueryParameters 
        {
            /// <summary>Maximum records per page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("limit")]
            public string? Limit { get; set; }
#nullable restore
#else
            [QueryParameter("limit")]
            public string Limit { get; set; }
#endif
            /// <summary>Location identifier filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("location_identifier")]
            public string? LocationIdentifier { get; set; }
#nullable restore
#else
            [QueryParameter("location_identifier")]
            public string LocationIdentifier { get; set; }
#endif
            /// <summary>Record offset for pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>Sort expression.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
