// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Forwarding.Documents;
using Soenneker.Ups.OpenApiClient.Forwarding.Info;
using Soenneker.Ups.OpenApiClient.Forwarding.Orders;
using Soenneker.Ups.OpenApiClient.Forwarding.Quotes;
using Soenneker.Ups.OpenApiClient.Forwarding.Shipments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ups.OpenApiClient.Forwarding
{
    /// <summary>
    /// Builds and executes requests for operations under \Forwarding
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ForwardingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The documents property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Documents.DocumentsRequestBuilder Documents
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Documents.DocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Info.InfoRequestBuilder Info
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The quotes property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Quotes.QuotesRequestBuilder Quotes
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Quotes.QuotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shipments property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder Shipments
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.ForwardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Forwarding", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.ForwardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForwardingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Forwarding", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
