// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.ProtectedDeliveryToken.Pins.Token
{
    /// <summary>
    /// Builds and executes requests for operations under \ProtectedDeliveryToken\pins\token
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.ProtectedDeliveryToken.Pins.Token.TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ProtectedDeliveryToken/pins/token", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.ProtectedDeliveryToken.Pins.Token.TokenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ProtectedDeliveryToken/pins/token", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint is used to get Pin by Token.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.GetPinByTokenResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.GetPinByTokenResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.GetPinByTokenResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.GetPinByTokenResponse>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.GetPinByTokenResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint is used to generate a token using Shipper generated PIN
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenResponse"/></returns>
        /// <param name="body">This request is sent to generate a token for a given Pin.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 415 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenResponse?> PostAsync(global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenResponse> PostAsync(global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "415", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ProtectedDeliveryTokenErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenResponse>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint is used to get Pin by Token.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This endpoint is used to generate a token using Shipper generated PIN
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">This request is sent to generate a token for a given Pin.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.GenerateTokenRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.ProtectedDeliveryToken.Pins.Token.TokenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.ProtectedDeliveryToken.Pins.Token.TokenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.ProtectedDeliveryToken.Pins.Token.TokenRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
