// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Models;
using Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.ChildShipments;
using Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.Closeout;
using Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.LtlChildShipments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \TradeDirect\master-shipments\{usi-number}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsiNumberItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The childShipments property</summary>
        public global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.ChildShipments.ChildShipmentsRequestBuilder ChildShipments
        {
            get => new global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.ChildShipments.ChildShipmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The closeout property</summary>
        public global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.Closeout.CloseoutRequestBuilder Closeout
        {
            get => new global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.Closeout.CloseoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ltlChildShipments property</summary>
        public global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.LtlChildShipments.LtlChildShipmentsRequestBuilder LtlChildShipments
        {
            get => new global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.LtlChildShipments.LtlChildShipmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsiNumberItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TradeDirect/master-shipments/{usi%2Dnumber}?shipper_account_number={shipper_account_number}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsiNumberItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TradeDirect/master-shipments/{usi%2Dnumber}?shipper_account_number={shipper_account_number}", rawUrl)
        {
        }
        /// <summary>
        /// This API allows users to delete a master shipment identified by a unique shipment identifier (USI) and the shipper&apos;s account number. The master shipment and its associated child shipments will be permanently removed.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder.UsiNumberItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder.UsiNumberItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.TradeDirectErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This API allows users to delete a master shipment identified by a unique shipment identifier (USI) and the shipper&apos;s account number. The master shipment and its associated child shipments will be permanently removed.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder.UsiNumberItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder.UsiNumberItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.TradeDirect.MasterShipments.Item.UsiNumberItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// This API allows users to delete a master shipment identified by a unique shipment identifier (USI) and the shipper&apos;s account number. The master shipment and its associated child shipments will be permanently removed.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsiNumberItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>The unique shipment identifier (USI) is used to create Master, LTL and Child shipments. Used for Freight shipments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_account_number")]
            public string? ShipperAccountNumber { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_account_number")]
            public string ShipperAccountNumber { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
