// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.CustomsDetailV2.Content.Fields.CustomsDetail;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ups.OpenApiClient.CustomsDetailV2.Content.Fields
{
    /// <summary>
    /// Builds and executes requests for operations under \CustomsDetailV2\content\fields
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FieldsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The customsDetail property</summary>
        public global::Soenneker.Ups.OpenApiClient.CustomsDetailV2.Content.Fields.CustomsDetail.CustomsDetailRequestBuilder CustomsDetail
        {
            get => new global::Soenneker.Ups.OpenApiClient.CustomsDetailV2.Content.Fields.CustomsDetail.CustomsDetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.CustomsDetailV2.Content.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CustomsDetailV2/content/fields", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.CustomsDetailV2.Content.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CustomsDetailV2/content/fields", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
