// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ups.OpenApiClient.Paperless
{
    /// <summary>
    /// Builds and executes requests for operations under \Paperless
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaperlessRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The paperlessdocuments property</summary>
        public global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.PaperlessdocumentsRequestBuilder Paperlessdocuments
        {
            get => new global::Soenneker.Ups.OpenApiClient.Paperless.Paperlessdocuments.PaperlessdocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Paperless.PaperlessRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaperlessRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Paperless", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Paperless.PaperlessRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaperlessRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Paperless", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
