// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Tracking\track\v1\shipment\details\{inquiryNumber}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithInquiryNumberItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInquiryNumberItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Tracking/track/v1/shipment/details/{inquiryNumber}{?count*,locale*,offset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInquiryNumberItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Tracking/track/v1/shipment/details/{inquiryNumber}{?count*,locale*,offset*}", rawUrl)
        {
        }
        /// <summary>
        /// Track Each Package in Shipment
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.Tracking_TrackApiResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.Tracking_TrackApiResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder.WithInquiryNumberItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.Tracking_TrackApiResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder.WithInquiryNumberItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Ups.OpenApiClient.Models.Tracking_Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.Tracking_TrackApiResponse>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.Tracking_TrackApiResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder.WithInquiryNumberItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder.WithInquiryNumberItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.Tracking.Track.V1.Shipment.Details.Item.WithInquiryNumberItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Track Each Package in Shipment
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithInquiryNumberItemRequestBuilderGetQueryParameters 
        {
            /// <summary>This is used to support pagination of package results. The count is the maximum number of packages to return starting with the offset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("count")]
            public string? Count { get; set; }
#nullable restore
#else
            [QueryParameter("count")]
            public string Count { get; set; }
#endif
            /// <summary>Language and country code of the user, separated by an underscore. Default value is &apos;en_US&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("locale")]
            public string? Locale { get; set; }
#nullable restore
#else
            [QueryParameter("locale")]
            public string Locale { get; set; }
#endif
            /// <summary>This is used to support pagination of package results. The offset is a 0-based index which defines the starting record to be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
