// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Shipping.Labels.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Ups.OpenApiClient.Shipping.Labels
{
    /// <summary>
    /// Builds and executes requests for operations under \Shipping\labels
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LabelsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Ups.OpenApiClient.Shipping.labels.item collection</summary>
        /// <param name="position">When UPS introduces new elements in the response that are not associated with new request elements, Subversion is used. This ensures backward compatibility. v1  original features of the application. No support for CODTurn-inPage, HighValueReport or InternationalForms features returned in the responsev1701  includes support for CODTurn-inPage features returned in the response.V1903 Length 5</param>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Shipping.Labels.Item.WithVersionItemRequestBuilder"/></returns>
        public global::Soenneker.Ups.OpenApiClient.Shipping.Labels.Item.WithVersionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("version", position);
                return new global::Soenneker.Ups.OpenApiClient.Shipping.Labels.Item.WithVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Shipping.Labels.LabelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LabelsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Shipping/labels", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Shipping.Labels.LabelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LabelsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Shipping/labels", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
