// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Response payload - object containing the list of account pickup preferences
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountPickupModifyResponse_payload : IAdditionalDataHolder, IParsable
    {
        /// <summary>UPS shipper account number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Emails associated with the account pickup preferences.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Emails { get; set; }
#nullable restore
#else
        public List<string> Emails { get; set; }
#endif
        /// <summary>Preferred locale for account pickup. Format follows &lt;a href=&quot;https://www.iso.org/iso-639-language-code.html&quot; target=&quot;_blank&quot;&gt;ISO 639M&lt;/a&gt; language code and region code combination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>Notification indicators container. Notifications can be sent in email or/and SMS.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.NotificationIndicators? NotificationIndicators { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.NotificationIndicators NotificationIndicators { get; set; }
#endif
        /// <summary>System generated id that represents the version of the document.</summary>
        public int? VersionNumber { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.AccountPickupModifyResponse_payload"/> and sets the default values.
        /// </summary>
        public AccountPickupModifyResponse_payload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.AccountPickupModifyResponse_payload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.AccountPickupModifyResponse_payload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.AccountPickupModifyResponse_payload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountNumber", n => { AccountNumber = n.GetStringValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "notificationIndicators", n => { NotificationIndicators = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.NotificationIndicators>(global::Soenneker.Ups.OpenApiClient.Models.NotificationIndicators.CreateFromDiscriminatorValue); } },
                { "versionNumber", n => { VersionNumber = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountNumber", AccountNumber);
            writer.WriteCollectionOfPrimitiveValues<string>("emails", Emails);
            writer.WriteStringValue("locale", Locale);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.NotificationIndicators>("notificationIndicators", NotificationIndicators);
            writer.WriteIntValue("versionNumber", VersionNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
