// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApolloAccessorialsResponseDetailsV1CodeOneOf3
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DDU")]
        #pragma warning disable CS1591
        Ddu,
        #pragma warning restore CS1591
    }
}
