// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>The units used to calculate weight</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApolloOrderSearchResponseV1Response_orders_items_weightUnit
    {
        [EnumMember(Value = "LB")]
        #pragma warning disable CS1591
        LB,
        #pragma warning restore CS1591
    }
}
