// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>The output format of the document.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApolloPrintManifestRequestV1_manifestFormat
    {
        [EnumMember(Value = "PDF")]
        #pragma warning disable CS1591
        PDF,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA")]
        #pragma warning disable CS1591
        DATA,
        #pragma warning restore CS1591
    }
}
