// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>The output format of the document.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ApolloOrderRequestV1LabelFormat
    {
        [EnumMember(Value = "PDF")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
        [EnumMember(Value = "PNG")]
        #pragma warning disable CS1591
        Png,
        #pragma warning restore CS1591
        [EnumMember(Value = "JPG")]
        #pragma warning disable CS1591
        Jpg,
        #pragma warning restore CS1591
        [EnumMember(Value = "BMP")]
        #pragma warning disable CS1591
        Bmp,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIFF")]
        #pragma warning disable CS1591
        Tiff,
        #pragma warning restore CS1591
        [EnumMember(Value = "SVG")]
        #pragma warning disable CS1591
        Svg,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA")]
        #pragma warning disable CS1591
        Data,
        #pragma warning restore CS1591
    }
}
