// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BookingResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bookingReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BookingReference { get; set; }
#nullable restore
#else
        public string BookingReference { get; set; }
#endif
        /// <summary>The cargoDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.AirOceanBookCargoDetails? CargoDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.AirOceanBookCargoDetails CargoDetails { get; set; }
#endif
        /// <summary>The confirmationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfirmationId { get; set; }
#nullable restore
#else
        public string ConfirmationId { get; set; }
#endif
        /// <summary>The createDate property</summary>
        public DateTimeOffset? CreateDate { get; set; }
        /// <summary>The quoteId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuoteId { get; set; }
#nullable restore
#else
        public string QuoteId { get; set; }
#endif
        /// <summary>The shipmentNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipmentNumber { get; set; }
#nullable restore
#else
        public string ShipmentNumber { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.BookingResponse"/> and sets the default values.
        /// </summary>
        public BookingResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.BookingResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.BookingResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.BookingResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bookingReference", n => { BookingReference = n.GetStringValue(); } },
                { "cargoDetails", n => { CargoDetails = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.AirOceanBookCargoDetails>(global::Soenneker.Ups.OpenApiClient.Models.AirOceanBookCargoDetails.CreateFromDiscriminatorValue); } },
                { "confirmationId", n => { ConfirmationId = n.GetStringValue(); } },
                { "createDate", n => { CreateDate = n.GetDateTimeOffsetValue(); } },
                { "quoteId", n => { QuoteId = n.GetStringValue(); } },
                { "shipmentNumber", n => { ShipmentNumber = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bookingReference", BookingReference);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.AirOceanBookCargoDetails>("cargoDetails", CargoDetails);
            writer.WriteStringValue("confirmationId", ConfirmationId);
            writer.WriteDateTimeOffsetValue("createDate", CreateDate);
            writer.WriteStringValue("quoteId", QuoteId);
            writer.WriteStringValue("shipmentNumber", ShipmentNumber);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
