// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>&quot;The shipment mode of transportation. If not one of the listed values then it will default to the first one from the import country.| Mode      | Description                                   || :--:      | :--                                           || DOM_AIR   | Domestic Air transportation                   || DOM_OCEAN | Domestic Ocean transportation                 || DOM_RAIL  | Domestic Rail transportation                  || DOM_TRUCK | Domestic Truck transportation                 || INT_AIR   | International Air transportation              || INT_OCEAN | International Ocean transportation            || INT_RAIL  | International Rail transportation             || INT_TRUCK | International/Interstate Truck transportation |&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BsisV1ShipmentTransModes
    {
        [EnumMember(Value = "DOM_AIR")]
        #pragma warning disable CS1591
        DomAir,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOM_OCEAN")]
        #pragma warning disable CS1591
        DomOcean,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOM_RAIL")]
        #pragma warning disable CS1591
        DomRail,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOM_TRUCK")]
        #pragma warning disable CS1591
        DomTruck,
        #pragma warning restore CS1591
        [EnumMember(Value = "INT_AIR")]
        #pragma warning disable CS1591
        IntAir,
        #pragma warning restore CS1591
        [EnumMember(Value = "INT_OCEAN")]
        #pragma warning disable CS1591
        IntOcean,
        #pragma warning restore CS1591
        [EnumMember(Value = "INT_RAIL")]
        #pragma warning disable CS1591
        IntRail,
        #pragma warning restore CS1591
        [EnumMember(Value = "INT_TRUCK")]
        #pragma warning disable CS1591
        IntTruck,
        #pragma warning restore CS1591
    }
}
