// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Object containing the details of each item in the shipment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BSIS_v1_ShipmentItemRequest : IParsable
    {
        /// <summary>This field is populated with the hscode description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The dimension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_dimension? Dimension { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_dimension Dimension { get; set; }
#endif
        /// <summary>Specifies the gross weight of the entire ShipmentItem, that is, the weight of all contained Products plus the Packaging weight, if any. Specifying this value overridesany weight value in Product and/or Packaging objects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_grossWeight? GrossWeight { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_grossWeight GrossWeight { get; set; }
#endif
        /// <summary>The ISO 3166 code of the shipment item country.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginCountryCode { get; set; }
#nullable restore
#else
        public string OriginCountryCode { get; set; }
#endif
        /// <summary>Part number or SKU, pre-approved for Garanteed Landed Cost service to identifier the item being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartNumber { get; set; }
#nullable restore
#else
        public string PartNumber { get; set; }
#endif
        /// <summary>Container to quantity information on items within the shipmentItem.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_quantity? Quantity { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_quantity Quantity { get; set; }
#endif
        /// <summary>The unitPrice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ChargeDetail? UnitPrice { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ChargeDetail UnitPrice { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "dimension", n => { Dimension = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_dimension>(global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_dimension.CreateFromDiscriminatorValue); } },
                { "grossWeight", n => { GrossWeight = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_grossWeight>(global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_grossWeight.CreateFromDiscriminatorValue); } },
                { "originCountryCode", n => { OriginCountryCode = n.GetStringValue(); } },
                { "partNumber", n => { PartNumber = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_quantity>(global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_quantity.CreateFromDiscriminatorValue); } },
                { "unitPrice", n => { UnitPrice = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ChargeDetail>(global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ChargeDetail.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_dimension>("dimension", Dimension);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_grossWeight>("grossWeight", GrossWeight);
            writer.WriteStringValue("originCountryCode", OriginCountryCode);
            writer.WriteStringValue("partNumber", PartNumber);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ShipmentItemRequest_quantity>("quantity", Quantity);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.BSIS_v1_ChargeDetail>("unitPrice", UnitPrice);
        }
    }
}
#pragma warning restore CS0618
