// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BSISV1ShipmentItemRequestDimension : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>package height (no limit).</summary>
        public decimal? Height { get; set; }
        /// <summary>package length (no limit).</summary>
        public decimal? Length { get; set; }
        /// <summary>Specifies the units of measure.</summary>
        public global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension_unitOfMeasure? UnitOfMeasure { get; set; }
        /// <summary>package width (no limit).</summary>
        public decimal? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension"/> and sets the default values.
        /// </summary>
        public BSISV1ShipmentItemRequestDimension()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "height", n => { Height = n.GetDecimalValue(); } },
                { "length", n => { Length = n.GetDecimalValue(); } },
                { "unitOfMeasure", n => { UnitOfMeasure = n.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension_unitOfMeasure>(); } },
                { "width", n => { Width = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("height", Height);
            writer.WriteDecimalValue("length", Length);
            writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.BSISV1ShipmentItemRequestDimension_unitOfMeasure>("unitOfMeasure", UnitOfMeasure);
            writer.WriteDecimalValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
