// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// This variable represents the product details. It is used to provide information about the product being shipped.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Child_Product : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;6-to-15-alphanumeric commodity code. Customs uses this code to determine what duties should be assessed on the commodity.  Applies to Invoice, Partial Invoice and USMCA. Required for USMCA and optional for Partial Invoice. Should be at least 6 alphanumeric. For USMCA: For each good described in Description of Goods field, identify the H.S. tariff classification to six digits. If the good is subject to a specific rule of origin in Annex 401 that requires eight digits, identify to eight digits, using the H.S. tariff classification of the country or territory into whose territory the good is imported.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommodityCode { get; set; }
#nullable restore
#else
        public string CommodityCode { get; set; }
#endif
        /// <summary>Country code of the product being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryOriginCode { get; set; }
#nullable restore
#else
        public string CountryOriginCode { get; set; }
#endif
        /// <summary>Description of the product being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Required for EEI form.  Applies to EEI form only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Product_EEIInformation? EEIInformation { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Product_EEIInformation EEIInformation { get; set; }
#endif
        /// <summary>Container tag for determining whether or not to exclude product information from a particular form.  If this container is not present we assume that the DEFAULT is selected which is &quot;none&quot; and all products will appear on all forms.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Product_ExcludeFromForm? ExcludeFromForm { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Product_ExcludeFromForm ExcludeFromForm { get; set; }
#endif
        /// <summary>&quot;Code indicating Domestic: Exports that have been produced, manufactured, or grown in the United States or Puerto Rico. This includes imported merchandise which has been enhanced in value or changed from the form in which imported by further manufacture or processing in the United States or Puerto Rico. Foreign: Merchandise that has entered the United States and is being exported again in the same condition as when imported.   Applies to EEI forms only. Required for EEI form.  Valid values:  D: Domestic; F: Foreign.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExportType { get; set; }
#nullable restore
#else
        public string ExportType { get; set; }
#endif
        /// <summary>If present, JNT will be used as the origin of country or territory code on the USMCA form and the Product/Origincountry or territoryCode tag will be ignored.  Applies to USMCA only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JointProductionIndicator { get; set; }
#nullable restore
#else
        public string JointProductionIndicator { get; set; }
#endif
        /// <summary>Any special marks, codes, and numbers that may appear on package.  Applies to CO Only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MarksAndNumbers { get; set; }
#nullable restore
#else
        public string MarksAndNumbers { get; set; }
#endif
        /// <summary>For each good described in the Description of Goods field, where the good is subject to a regional value content (RVC) requirement, indicate NC if the RVC is calculated according to the net cost method; otherwise, indicate NO. If the RVC is calculated over a period of time then indicate &quot;NC with begin/end date&quot; by passing code &quot;ND&quot;  Applies to USMCA only. Required for USMCA.  Valid values:- NC- ND- NO</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetCostCode { get; set; }
#nullable restore
#else
        public string NetCostCode { get; set; }
#endif
        /// <summary>Date Range for regional value content (RVC).  Applies to USMCA CO only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Product_NetCostDateRange? NetCostDateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Product_NetCostDateRange NetCostDateRange { get; set; }
#endif
        /// <summary>The total number of packages, cartons, or containers for the commodity.  Applicable for CO and is required. Should be numeric. Valid characters are 0 -9.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberOfPackagesPerCommodity { get; set; }
#nullable restore
#else
        public string NumberOfPackagesPerCommodity { get; set; }
#endif
        /// <summary>Number of units of the product being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberOfUnits { get; set; }
#nullable restore
#else
        public string NumberOfUnits { get; set; }
#endif
        /// <summary>Data Container holding package related information.  Required for packaging list, Air Freight Packing list and multi-piece Economy shipments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Product_PackingListInfo? PackingListInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Product_PackingListInfo PackingListInfo { get; set; }
#endif
        /// <summary>Indicates the criterion (A through F) for each good described in the Description of Goods field if applicable. The rules of origin are contained in Chapter Four and Annex 401. Additional rules are described in Annex 703.2 (certain agricultural goods), Annex 300-B, Appendix 6 (certain textile goods) and Annex 308.1 (certain automatic data processing goods and their parts).  Applies to USMCA only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferenceCriteria { get; set; }
#nullable restore
#else
        public string PreferenceCriteria { get; set; }
#endif
        /// <summary>&quot;Indicate the following:  Yes - If shipper is the producer of the good. If not, state 02, 03, and 04 depending on whether this certificate was based upon:  No [1] - Knowledge of whether the good qualifies as an originating good. No [2] - Reliance on the producers written representation (other than a Certificate of Origin) that the good qualifies as an originating good. No [3] - A completed and signed Certificate for the good voluntarily provided to the exporter by the producer.  Applicable for USMCA and is required. Valid values: Yes, No [1], No [2], and No [3].&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProducerInfo { get; set; }
#nullable restore
#else
        public string ProducerInfo { get; set; }
#endif
        /// <summary>Product number of the product being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductNumber { get; set; }
#nullable restore
#else
        public string ProductNumber { get; set; }
#endif
        /// <summary>The shipping weight, including containers, for each commodity with a separate Harmonized Tariff Code / Schedule B Number. This weight does not include carrier equipment.  Applies to CO and EEI forms only. Required for CO and EEI forms.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Product_ProductWeight? ProductWeight { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Product_ProductWeight ProductWeight { get; set; }
#endif
        /// <summary>Container tag for the schedule B information of a commodity.  Applies to EEI forms only. Required for EEI form</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Product_ScheduleB? ScheduleB { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Product_ScheduleB ScheduleB { get; set; }
#endif
        /// <summary>&quot;This amount will always be USD.  Applies to EEI forms only. Required for EEI form. Valid characters are 0-9 and \&apos;.\&apos; (Decimal point). Limit to 2 digit after the decimal. The maximum length of the field is 15 including \&apos;.\&apos; and can hold up to 2 decimal places.Note: This value is calculated based on the Product/Unit/Value and /Product/Unit/Number (Number of Units * Price per Unit). If the total value is incorrect it will be replaced by the actual calculated total value.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SEDTotalValue { get; set; }
#nullable restore
#else
        public string SEDTotalValue { get; set; }
#endif
        /// <summary>Invoice Commodity Level Tax Collected Code for each shipment commodity line.Taxes paid Indicator is only applicable for shipments to Singapore. [TaxesPaid = 0 - No on Report], [TaxesPaid = 1 -Yes on Report], [TaxesPaid = empty - null on Report], [If TaxesPaid is not passed in input request = null on Report]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxesPaid { get; set; }
#nullable restore
#else
        public string TaxesPaid { get; set; }
#endif
        /// <summary>Unit of Measure for the product being shipped.Valid values are : - BA = Barrel - BE = Bundle - BG = Bag - BH =Bunch - BOX = Box - BT = Bolt - LB =Pound - LBS = Pounds - L = Liter - M = Meter - NMB = Number - PA = Packet - BU = Butt - CI =Canister - CM =Centimeter - CON = Container - CR = Crate - CS =Case - CT =Carton - CY =Cylinder - DOZ = Dozen - EA = Each - EN =Envelope - FT =Feet - KG =Kilogram - KGS = Kilograms - PAL = Pallet - PC = Piece - PCS = Pieces - PF = Proof Liters - OTH = Other - PKG = Package - PR = Pair - PRS = Pairs - RL = Roll - SET = Set - SME = Square Meters - SYD = Square Yards - TU =Tube - YD =Yard</summary>
        public global::Soenneker.Ups.OpenApiClient.Models.Child_Product_UnitOfMeasure? UnitOfMeasure { get; set; }
        /// <summary>Price per unit of the product being shipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitPrice { get; set; }
#nullable restore
#else
        public string UnitPrice { get; set; }
#endif
        /// <summary>&quot;Includes the following information for used self-propelled vehicles as defined in Customs regulations 19 CFR 192.1: The unique Vehicle Identification Number (VIN) in the proper format. Or The Product Identification Number (PIN) for those used self-propelled vehicles for which there are no VINs.  Or the Vehicle Title Number.  Applies to EEI forms only.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VehicleID { get; set; }
#nullable restore
#else
        public string VehicleID { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.Child_Product"/> and sets the default values.
        /// </summary>
        public Child_Product()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.Child_Product"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.Child_Product CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.Child_Product();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CommodityCode", n => { CommodityCode = n.GetStringValue(); } },
                { "CountryOriginCode", n => { CountryOriginCode = n.GetStringValue(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "EEIInformation", n => { EEIInformation = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_EEIInformation>(global::Soenneker.Ups.OpenApiClient.Models.Product_EEIInformation.CreateFromDiscriminatorValue); } },
                { "ExcludeFromForm", n => { ExcludeFromForm = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_ExcludeFromForm>(global::Soenneker.Ups.OpenApiClient.Models.Product_ExcludeFromForm.CreateFromDiscriminatorValue); } },
                { "ExportType", n => { ExportType = n.GetStringValue(); } },
                { "JointProductionIndicator", n => { JointProductionIndicator = n.GetStringValue(); } },
                { "MarksAndNumbers", n => { MarksAndNumbers = n.GetStringValue(); } },
                { "NetCostCode", n => { NetCostCode = n.GetStringValue(); } },
                { "NetCostDateRange", n => { NetCostDateRange = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_NetCostDateRange>(global::Soenneker.Ups.OpenApiClient.Models.Product_NetCostDateRange.CreateFromDiscriminatorValue); } },
                { "NumberOfPackagesPerCommodity", n => { NumberOfPackagesPerCommodity = n.GetStringValue(); } },
                { "NumberOfUnits", n => { NumberOfUnits = n.GetStringValue(); } },
                { "PackingListInfo", n => { PackingListInfo = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_PackingListInfo>(global::Soenneker.Ups.OpenApiClient.Models.Product_PackingListInfo.CreateFromDiscriminatorValue); } },
                { "PreferenceCriteria", n => { PreferenceCriteria = n.GetStringValue(); } },
                { "ProducerInfo", n => { ProducerInfo = n.GetStringValue(); } },
                { "ProductNumber", n => { ProductNumber = n.GetStringValue(); } },
                { "ProductWeight", n => { ProductWeight = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_ProductWeight>(global::Soenneker.Ups.OpenApiClient.Models.Product_ProductWeight.CreateFromDiscriminatorValue); } },
                { "SEDTotalValue", n => { SEDTotalValue = n.GetStringValue(); } },
                { "ScheduleB", n => { ScheduleB = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_ScheduleB>(global::Soenneker.Ups.OpenApiClient.Models.Product_ScheduleB.CreateFromDiscriminatorValue); } },
                { "TaxesPaid", n => { TaxesPaid = n.GetStringValue(); } },
                { "UnitOfMeasure", n => { UnitOfMeasure = n.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.Child_Product_UnitOfMeasure>(); } },
                { "UnitPrice", n => { UnitPrice = n.GetStringValue(); } },
                { "VehicleID", n => { VehicleID = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("CommodityCode", CommodityCode);
            writer.WriteStringValue("CountryOriginCode", CountryOriginCode);
            writer.WriteStringValue("Description", Description);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_EEIInformation>("EEIInformation", EEIInformation);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_ExcludeFromForm>("ExcludeFromForm", ExcludeFromForm);
            writer.WriteStringValue("ExportType", ExportType);
            writer.WriteStringValue("JointProductionIndicator", JointProductionIndicator);
            writer.WriteStringValue("MarksAndNumbers", MarksAndNumbers);
            writer.WriteStringValue("NetCostCode", NetCostCode);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_NetCostDateRange>("NetCostDateRange", NetCostDateRange);
            writer.WriteStringValue("NumberOfPackagesPerCommodity", NumberOfPackagesPerCommodity);
            writer.WriteStringValue("NumberOfUnits", NumberOfUnits);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_PackingListInfo>("PackingListInfo", PackingListInfo);
            writer.WriteStringValue("PreferenceCriteria", PreferenceCriteria);
            writer.WriteStringValue("ProducerInfo", ProducerInfo);
            writer.WriteStringValue("ProductNumber", ProductNumber);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_ProductWeight>("ProductWeight", ProductWeight);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Product_ScheduleB>("ScheduleB", ScheduleB);
            writer.WriteStringValue("SEDTotalValue", SEDTotalValue);
            writer.WriteStringValue("TaxesPaid", TaxesPaid);
            writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.Child_Product_UnitOfMeasure>("UnitOfMeasure", UnitOfMeasure);
            writer.WriteStringValue("UnitPrice", UnitPrice);
            writer.WriteStringValue("VehicleID", VehicleID);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
