// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomDetailsPostFieldsRequestv2ProductsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The tariff code for the product for the selected import country and process type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommodityCode { get; set; }
#nullable restore
#else
        public string CommodityCode { get; set; }
#endif
        /// <summary>The sequence number of the product line item on the commercial invoice. Use this field to identify which invoice line item the customs detail data applies to. For example, enter 1 for the first invoice line item, 2 for the second invoice line item, and so on. This helps correlate customs detail data with the correct product, shipment data, and customs declaration.</summary>
        public int? LineNumber { get; set; }
        /// <summary>Provide a clear and accurate description of the product exactly as it appears on the Commercial Invoice and any other applicable international shipping documents. The description should clearly identify the item and, when relevant, its intended use. Avoid generic terms such as parts, samples, goods, accessories, or merchandise, as these descriptions may not provide sufficient detail for customs authorities and could result in clearance delays or requests for additional information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductDescription { get; set; }
#nullable restore
#else
        public string ProductDescription { get; set; }
#endif
        /// <summary>A customer-defined identifier for the product. This should match the product part number, SKU, item number, or reference number provided for the Part Number on the Commercial Invoice. Use the same value to help UPS associate Customs Detail API product data with the corresponding invoice line item in the shipment request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>Unbounded list of containers for product metadata groups. Include at least one metadata entry in either ShipmentMetaData or ProductMetaData.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsRequestMetaDatav2Item>? ProductMetaData { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsRequestMetaDatav2Item> ProductMetaData { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsPostFieldsRequestv2ProductsItem"/> and sets the default values.
        /// </summary>
        public CustomDetailsPostFieldsRequestv2ProductsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsPostFieldsRequestv2ProductsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsPostFieldsRequestv2ProductsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsPostFieldsRequestv2ProductsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commodityCode", n => { CommodityCode = n.GetStringValue(); } },
                { "lineNumber", n => { LineNumber = n.GetIntValue(); } },
                { "productDescription", n => { ProductDescription = n.GetStringValue(); } },
                { "productId", n => { ProductId = n.GetStringValue(); } },
                { "productMetaData", n => { ProductMetaData = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsRequestMetaDatav2Item>(global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsRequestMetaDatav2Item.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("commodityCode", CommodityCode);
            writer.WriteIntValue("lineNumber", LineNumber);
            writer.WriteStringValue("productDescription", ProductDescription);
            writer.WriteStringValue("productId", ProductId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CustomDetailsRequestMetaDatav2Item>("productMetaData", ProductMetaData);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
