// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeliveryInterceptChargesResponseV2ResponseAllOf2ChargeInfoItemPackageWeightUomWrapperValue
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "LBS")]
        #pragma warning disable CS1591
        Lbs,
        #pragma warning restore CS1591
    }
}
