// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeliveryInterceptRequestV2RequestType_Wrapper_2_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SC")]
        #pragma warning disable CS1591
        SC,
        #pragma warning restore CS1591
    }
}
