// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf1"/>, <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf2"/>, <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf3"/>, <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf4"/>, <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf5"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeliveryInterceptRequestV2RequestType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf1"/></summary>
        public global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf1? DeliveryInterceptRequestV2RequestTypeOneOf1 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf2"/></summary>
        public global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf2? DeliveryInterceptRequestV2RequestTypeOneOf2 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf3"/></summary>
        public global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf3? DeliveryInterceptRequestV2RequestTypeOneOf3 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf4"/></summary>
        public global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf4? DeliveryInterceptRequestV2RequestTypeOneOf4 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf5"/></summary>
        public global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf5? DeliveryInterceptRequestV2RequestTypeOneOf5 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestType();
            if(parseNode.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf1>() is global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf1 deliveryInterceptRequestV2RequestTypeOneOf1Value)
            {
                result.DeliveryInterceptRequestV2RequestTypeOneOf1 = deliveryInterceptRequestV2RequestTypeOneOf1Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf2>() is global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf2 deliveryInterceptRequestV2RequestTypeOneOf2Value)
            {
                result.DeliveryInterceptRequestV2RequestTypeOneOf2 = deliveryInterceptRequestV2RequestTypeOneOf2Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf3>() is global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf3 deliveryInterceptRequestV2RequestTypeOneOf3Value)
            {
                result.DeliveryInterceptRequestV2RequestTypeOneOf3 = deliveryInterceptRequestV2RequestTypeOneOf3Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf4>() is global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf4 deliveryInterceptRequestV2RequestTypeOneOf4Value)
            {
                result.DeliveryInterceptRequestV2RequestTypeOneOf4 = deliveryInterceptRequestV2RequestTypeOneOf4Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf5>() is global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf5 deliveryInterceptRequestV2RequestTypeOneOf5Value)
            {
                result.DeliveryInterceptRequestV2RequestTypeOneOf5 = deliveryInterceptRequestV2RequestTypeOneOf5Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DeliveryInterceptRequestV2RequestTypeOneOf1 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf1>(null, DeliveryInterceptRequestV2RequestTypeOneOf1);
            }
            else if(DeliveryInterceptRequestV2RequestTypeOneOf2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf2>(null, DeliveryInterceptRequestV2RequestTypeOneOf2);
            }
            else if(DeliveryInterceptRequestV2RequestTypeOneOf3 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf3>(null, DeliveryInterceptRequestV2RequestTypeOneOf3);
            }
            else if(DeliveryInterceptRequestV2RequestTypeOneOf4 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf4>(null, DeliveryInterceptRequestV2RequestTypeOneOf4);
            }
            else if(DeliveryInterceptRequestV2RequestTypeOneOf5 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Ups.OpenApiClient.Models.DeliveryInterceptRequestV2RequestTypeOneOf5>(null, DeliveryInterceptRequestV2RequestTypeOneOf5);
            }
        }
    }
}
#pragma warning restore CS0618
