// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>RECEIVER DID NOT WANT, REFUSED DELIVERY</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeliveryInterceptRequestV2ReasonForReturnOneOf7
    {
        [EnumMember(Value = "KR")]
        #pragma warning disable CS1591
        Kr,
        #pragma warning restore CS1591
    }
}
