// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Contains information about updated shipping address.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Exception_UpdatedAddress : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Container for information about updated shipping address. It will be returned if there is any update due to exception.**NOTE:** For versions &gt;= v3, this element will always be returned as an array. For requests using version = v1 and v2, this element will be returned as an array if there is more than one object and a single object if there is only 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.UpdatedAddress_AddressExtendedInformation>? AddressExtendedInformation { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.UpdatedAddress_AddressExtendedInformation> AddressExtendedInformation { get; set; }
#endif
        /// <summary>Consignee&apos;s name for package shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConsigneeName { get; set; }
#nullable restore
#else
        public string ConsigneeName { get; set; }
#endif
        /// <summary>Abbreviated country or territory name of updated shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>Abbreviated state or province name of updated shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PoliticalDivision1 { get; set; }
#nullable restore
#else
        public string PoliticalDivision1 { get; set; }
#endif
        /// <summary>City name of updated shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PoliticalDivision2 { get; set; }
#nullable restore
#else
        public string PoliticalDivision2 { get; set; }
#endif
        /// <summary>The neighborhood, town, barrio etc. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PoliticalDivision3 { get; set; }
#nullable restore
#else
        public string PoliticalDivision3 { get; set; }
#endif
        /// <summary>Postal Code of updated shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostcodePrimaryLow { get; set; }
#nullable restore
#else
        public string PostcodePrimaryLow { get; set; }
#endif
        /// <summary>Street name of updated shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetName { get; set; }
#nullable restore
#else
        public string StreetName { get; set; }
#endif
        /// <summary>Street number of updated shipping address. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetNumberLow { get; set; }
#nullable restore
#else
        public string StreetNumberLow { get; set; }
#endif
        /// <summary>Street prefix of updated shipping address, e.g. N, SE. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetPrefix { get; set; }
#nullable restore
#else
        public string StreetPrefix { get; set; }
#endif
        /// <summary>Street suffix of updated shipping address, e.g. N, SE. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetSuffix { get; set; }
#nullable restore
#else
        public string StreetSuffix { get; set; }
#endif
        /// <summary>Street type of updated shipping address, e.g. ST. It will be returned if there is any update due to exception.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetType { get; set; }
#nullable restore
#else
        public string StreetType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.Exception_UpdatedAddress"/> and sets the default values.
        /// </summary>
        public Exception_UpdatedAddress()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.Exception_UpdatedAddress"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.Exception_UpdatedAddress CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.Exception_UpdatedAddress();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddressExtendedInformation", n => { AddressExtendedInformation = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.UpdatedAddress_AddressExtendedInformation>(global::Soenneker.Ups.OpenApiClient.Models.UpdatedAddress_AddressExtendedInformation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ConsigneeName", n => { ConsigneeName = n.GetStringValue(); } },
                { "CountryCode", n => { CountryCode = n.GetStringValue(); } },
                { "PoliticalDivision1", n => { PoliticalDivision1 = n.GetStringValue(); } },
                { "PoliticalDivision2", n => { PoliticalDivision2 = n.GetStringValue(); } },
                { "PoliticalDivision3", n => { PoliticalDivision3 = n.GetStringValue(); } },
                { "PostcodePrimaryLow", n => { PostcodePrimaryLow = n.GetStringValue(); } },
                { "StreetName", n => { StreetName = n.GetStringValue(); } },
                { "StreetNumberLow", n => { StreetNumberLow = n.GetStringValue(); } },
                { "StreetPrefix", n => { StreetPrefix = n.GetStringValue(); } },
                { "StreetSuffix", n => { StreetSuffix = n.GetStringValue(); } },
                { "StreetType", n => { StreetType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.UpdatedAddress_AddressExtendedInformation>("AddressExtendedInformation", AddressExtendedInformation);
            writer.WriteStringValue("ConsigneeName", ConsigneeName);
            writer.WriteStringValue("CountryCode", CountryCode);
            writer.WriteStringValue("PoliticalDivision1", PoliticalDivision1);
            writer.WriteStringValue("PoliticalDivision2", PoliticalDivision2);
            writer.WriteStringValue("PoliticalDivision3", PoliticalDivision3);
            writer.WriteStringValue("PostcodePrimaryLow", PostcodePrimaryLow);
            writer.WriteStringValue("StreetName", StreetName);
            writer.WriteStringValue("StreetNumberLow", StreetNumberLow);
            writer.WriteStringValue("StreetPrefix", StreetPrefix);
            writer.WriteStringValue("StreetSuffix", StreetSuffix);
            writer.WriteStringValue("StreetType", StreetType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
