// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>&quot;Image format type for the label requested by customer.| Code   | Description   || :----: | :-----------: || ZPL    | ZPL format    || EPL    | EPL format    || STARPL | STARPL format || SPL    | SPL format    || PNG    | PNG format    || PDF    | PDF format    || GIF    | GIF format    |&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LabelDetailsOpTyp
    {
        [EnumMember(Value = "ZPL")]
        #pragma warning disable CS1591
        Zpl,
        #pragma warning restore CS1591
        [EnumMember(Value = "EPL")]
        #pragma warning disable CS1591
        Epl,
        #pragma warning restore CS1591
        [EnumMember(Value = "STARPL")]
        #pragma warning disable CS1591
        Starpl,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPL")]
        #pragma warning disable CS1591
        Spl,
        #pragma warning restore CS1591
        [EnumMember(Value = "PNG")]
        #pragma warning disable CS1591
        Png,
        #pragma warning restore CS1591
        [EnumMember(Value = "PDF")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
        [EnumMember(Value = "GIF")]
        #pragma warning disable CS1591
        Gif,
        #pragma warning restore CS1591
    }
}
