// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Container to hold Mail Innovations shipments label. The elements needed to render a label on a printer or in a browser. Specifies the format in which GraphicImage is represented. If LabelImageFormat is GIF, LabelImage contains GraphicImage and HTMLImage. Otherwise, it contains only GraphicImage.   Applicable for Single Mail Innovations Returns and Dual Mail Innovations Returns shipment. Returned only if MailInnovationsTrackingNumber is provided in request.If LabelImageFormat requested was PDF and TrackingNumber was present along with MailInnovationsTrackingNumber in the request, only LabelImage container is returned. MailInnovationsLabelImage will not be returned. In that case, the labels for Small Package Tracking Number and Mail Innovations Tracking Number will be stitched in single PDF file.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LabelResultsMailInnovationsLabelImage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Base 64 encoded graphic image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GraphicImage { get; set; }
#nullable restore
#else
        public string GraphicImage { get; set; }
#endif
        /// <summary>Base 64 encoded html browser image rendering software. This is only returned for GIF image formats.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HTMLImage { get; set; }
#nullable restore
#else
        public string HTMLImage { get; set; }
#endif
        /// <summary>Base 64 encoded graphic image of the Warsaw text and signature box.  EPL2, ZPL and SPL labels. The image will be returned for non-US based shipments. One image will be given per shipment and it will be in the first PackageResults container.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternationalSignatureGraphicImage { get; set; }
#nullable restore
#else
        public string InternationalSignatureGraphicImage { get; set; }
#endif
        /// <summary>The format of a label image byte stream.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.MailInnovationsLabelImageLabelImageFormat? LabelImageFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.MailInnovationsLabelImageLabelImageFormat LabelImageFormat { get; set; }
#endif
        /// <summary>&quot;PDF-417 is a two-dimensional barcode, which can store up to about 1,800 printable ASCII characters or 1,100 binary characters per symbol. The symbol is rectangular. The PDF417 image will be returned when the shipment is trans-border and the service option is one of the following: Standard, Express Saver or Express Plus.  The image is Base 64 encoded and only returned for GIF image format&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PDF417 { get; set; }
#nullable restore
#else
        public string PDF417 { get; set; }
#endif
        /// <summary>This is only returned if the label link is requested to be returned and only at the first package result  Applicable for following types of shipments:Print/Electronic Return Label</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? URL { get; set; }
#nullable restore
#else
        public string URL { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.LabelResultsMailInnovationsLabelImage"/> and sets the default values.
        /// </summary>
        public LabelResultsMailInnovationsLabelImage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.LabelResultsMailInnovationsLabelImage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.LabelResultsMailInnovationsLabelImage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.LabelResultsMailInnovationsLabelImage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "GraphicImage", n => { GraphicImage = n.GetStringValue(); } },
                { "HTMLImage", n => { HTMLImage = n.GetStringValue(); } },
                { "InternationalSignatureGraphicImage", n => { InternationalSignatureGraphicImage = n.GetStringValue(); } },
                { "LabelImageFormat", n => { LabelImageFormat = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.MailInnovationsLabelImageLabelImageFormat>(global::Soenneker.Ups.OpenApiClient.Models.MailInnovationsLabelImageLabelImageFormat.CreateFromDiscriminatorValue); } },
                { "PDF417", n => { PDF417 = n.GetStringValue(); } },
                { "URL", n => { URL = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("GraphicImage", GraphicImage);
            writer.WriteStringValue("HTMLImage", HTMLImage);
            writer.WriteStringValue("InternationalSignatureGraphicImage", InternationalSignatureGraphicImage);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.MailInnovationsLabelImageLabelImageFormat>("LabelImageFormat", LabelImageFormat);
            writer.WriteStringValue("PDF417", PDF417);
            writer.WriteStringValue("URL", URL);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
