// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Container for Response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocatorResponse_Response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If an error is encountered during the interchange, the Response contains an error. If the error is present, then the ErrorSeverity and ErrorCode are required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Response_Error? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Response_Error Error { get; set; }
#endif
        /// <summary>Identifies the success or failure of the interchange. 1-Success0-Failure</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponseStatusCode { get; set; }
#nullable restore
#else
        public string ResponseStatusCode { get; set; }
#endif
        /// <summary>Describes the Response Status Code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponseStatusDescription { get; set; }
#nullable restore
#else
        public string ResponseStatusDescription { get; set; }
#endif
        /// <summary>Container for customer provided data and the XPCI Version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Locator_Response_TransactionReference? TransactionReference { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Locator_Response_TransactionReference TransactionReference { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.LocatorResponse_Response"/> and sets the default values.
        /// </summary>
        public LocatorResponse_Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.LocatorResponse_Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.LocatorResponse_Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.LocatorResponse_Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Error", n => { Error = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Response_Error>(global::Soenneker.Ups.OpenApiClient.Models.Response_Error.CreateFromDiscriminatorValue); } },
                { "ResponseStatusCode", n => { ResponseStatusCode = n.GetStringValue(); } },
                { "ResponseStatusDescription", n => { ResponseStatusDescription = n.GetStringValue(); } },
                { "TransactionReference", n => { TransactionReference = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Locator_Response_TransactionReference>(global::Soenneker.Ups.OpenApiClient.Models.Locator_Response_TransactionReference.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Response_Error>("Error", Error);
            writer.WriteStringValue("ResponseStatusCode", ResponseStatusCode);
            writer.WriteStringValue("ResponseStatusDescription", ResponseStatusDescription);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Locator_Response_TransactionReference>("TransactionReference", TransactionReference);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
