// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// The Location search criteria container allows the user to further define the basis to which they wish to receive the UPS locations. Only relevant when the user requests a Location search (request option 1).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocatorRequestLocationSearchCriteria : IAdditionalDataHolder, IParsable
    {
        /// <summary>Applicable for request option 64 only. This contains inclusion and exclusion criteria for address search. It also contains Account Number and Access Point Public ID search elements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaAccessPointSearch? AccessPointSearch { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaAccessPointSearch AccessPointSearch { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Brexit Filter. Applicable for country code GB; Pass the PostalCode for the address in the location search if Brexit functionality is desired. UAPs with postal code starts with BT returned when brexit filter starts with BT, else UAPs returned with non BT postal code. Applicable for UAP and Proximal building search.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrexitFilter { get; set; }
#nullable restore
#else
        public string BrexitFilter { get; set; }
#endif
        /// <summary>Freight Will Call Search Container. Required if SearchOption is &apos;05-Freight Will Call Search&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaFreightWillCallSearch? FreightWillCallSearch { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaFreightWillCallSearch FreightWillCallSearch { get; set; }
#endif
        /// <summary>If present, indicates the maximum number of locations the client wishes to receive in response; ranges from 1 to 50 with a default value of 5.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaximumListSize { get; set; }
#nullable restore
#else
        public string MaximumListSize { get; set; }
#endif
        /// <summary>Container to hold open times of the Location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaOpenTimeCriteria? OpenTimeCriteria { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaOpenTimeCriteria OpenTimeCriteria { get; set; }
#endif
        /// <summary>The SearchOption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaSearchOption>? SearchOption { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaSearchOption> SearchOption { get; set; }
#endif
        /// <summary>Defines the maximum radius the user wishes to search for a UPS location. If the user does not specify, the default value is 100 miles. Whole numbers only. Valid values are:5-100 for UnitOfMeasure MI5-150 for UnitOfMesaure KM</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchRadius { get; set; }
#nullable restore
#else
        public string SearchRadius { get; set; }
#endif
        /// <summary>Allows for users to further define the search criteria. Refer to the rules specified in Service Search section.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaServiceSearch? ServiceSearch { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaServiceSearch ServiceSearch { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.LocatorRequestLocationSearchCriteria"/> and sets the default values.
        /// </summary>
        public LocatorRequestLocationSearchCriteria()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.LocatorRequestLocationSearchCriteria"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.LocatorRequestLocationSearchCriteria CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.LocatorRequestLocationSearchCriteria();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccessPointSearch", n => { AccessPointSearch = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaAccessPointSearch>(global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaAccessPointSearch.CreateFromDiscriminatorValue); } },
                { "BrexitFilter", n => { BrexitFilter = n.GetStringValue(); } },
                { "FreightWillCallSearch", n => { FreightWillCallSearch = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaFreightWillCallSearch>(global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaFreightWillCallSearch.CreateFromDiscriminatorValue); } },
                { "MaximumListSize", n => { MaximumListSize = n.GetStringValue(); } },
                { "OpenTimeCriteria", n => { OpenTimeCriteria = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaOpenTimeCriteria>(global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaOpenTimeCriteria.CreateFromDiscriminatorValue); } },
                { "SearchOption", n => { SearchOption = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaSearchOption>(global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaSearchOption.CreateFromDiscriminatorValue)?.AsList(); } },
                { "SearchRadius", n => { SearchRadius = n.GetStringValue(); } },
                { "ServiceSearch", n => { ServiceSearch = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaServiceSearch>(global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaServiceSearch.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaAccessPointSearch>("AccessPointSearch", AccessPointSearch);
            writer.WriteStringValue("BrexitFilter", BrexitFilter);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaFreightWillCallSearch>("FreightWillCallSearch", FreightWillCallSearch);
            writer.WriteStringValue("MaximumListSize", MaximumListSize);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaOpenTimeCriteria>("OpenTimeCriteria", OpenTimeCriteria);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaSearchOption>("SearchOption", SearchOption);
            writer.WriteStringValue("SearchRadius", SearchRadius);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.LocationSearchCriteriaServiceSearch>("ServiceSearch", ServiceSearch);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
