// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>Freight class of the handling unit.Valid values are:- 50 = over 50 lbs - Fits on standard shrink-wrapped 4X4 pallet, very durable- 55 = 35-50 pounds - Bricks, cement, mortar, hardwood flooring- 60 = 30-35 pounds - Car accessories &amp; car parts- 65 = 22.5-30 pounds - Car accessories &amp; car parts, bottled beverages, books in boxes- 70 = 15 to 22.5 pounds - Car accessories &amp; car parts, food items, automobile engines- 77.5 = 13.5 to 15 pounds - Tires, bathroom fixtures- 85 =12-13.5 pounds - Crated machinery, cast iron stoves- 92.5 = 10.5-12 pounds - Computers, monitors, refrigerators- 100 =9-10.5 pounds - Boat covers, car covers, canvas, wine cases, caskets- 110 =8-9 pounds - Cabinets, framed artwork, table saw- 125 =7-8 pounds - Small Household appliances- 150 =6-7 pounds - Auto sheet metal parts, bookcases- 175 =5-6 pounds - Clothing, couches stuffed furniture- 200 =4-5 pounds - Auto sheet metal parts, aircraft parts, aluminum table, packaged mattresses- 250 =3-4 pounds - Bamboo furniture, mattress and box spring, plasma TV- 300 =2-3 pounds - Wood cabinets, tables, chairs setup, model boats- 400 =1-2 pounds - Deer antlers- 500 =Less than 1 lbs - Bags of gold dust, ping pong balls</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LTLHandlingUnits_FreightClass
    {
        [EnumMember(Value = "50")]
        #pragma warning disable CS1591
        FiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "55")]
        #pragma warning disable CS1591
        FiveFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "60")]
        #pragma warning disable CS1591
        SixZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "65")]
        #pragma warning disable CS1591
        SixFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "70")]
        #pragma warning disable CS1591
        SevenZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "77.5")]
        #pragma warning disable CS1591
        SevenSevenFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "85")]
        #pragma warning disable CS1591
        EightFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "92.5")]
        #pragma warning disable CS1591
        NineTwoFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "100")]
        #pragma warning disable CS1591
        OneZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "110")]
        #pragma warning disable CS1591
        OneOneZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "125")]
        #pragma warning disable CS1591
        OneTwoFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "150")]
        #pragma warning disable CS1591
        OneFiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "175")]
        #pragma warning disable CS1591
        OneSevenFive,
        #pragma warning restore CS1591
        [EnumMember(Value = "200")]
        #pragma warning disable CS1591
        TwoZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "250")]
        #pragma warning disable CS1591
        TwoFiveZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "300")]
        #pragma warning disable CS1591
        ThreeZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "400")]
        #pragma warning disable CS1591
        FourZeroZero,
        #pragma warning restore CS1591
        [EnumMember(Value = "500")]
        #pragma warning disable CS1591
        FiveZeroZero,
        #pragma warning restore CS1591
    }
}
