// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>The type of declaration statement. Can be invoice or USMCA. Valid values: - Invoice =Invoice declaration- USMCA = USMCA declaration</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Master_TradeComplianceDetails_DeclarationStatement
    {
        [EnumMember(Value = "Invoice")]
        #pragma warning disable CS1591
        Invoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "USMCA")]
        #pragma warning disable CS1591
        USMCA,
        #pragma warning restore CS1591
    }
}
