// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>The terms of sale for the invoice. Valid values: - CFR =Cost and Freight- CIF =Cost Insurance and Freight- CIP =Carriage and Insurance Paid- CPT =Carriage Paid To- DAF =Delivered at Frontier- DAP =Delivered at Place- DAT =Delivered at Terminal- DDP =Delivery Duty Paid- DDU =Delivery Duty Unpaid- DEQ =Delivered Ex Quay- DES =Delivered Ex Ship- EXW =Ex Works- FAS =Free Alongside Ship- FCA =Free Carrier- FOB =Free On Board  </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Master_TradeComplianceDetails_TermsOfShipment
    {
        [EnumMember(Value = "CFR")]
        #pragma warning disable CS1591
        CFR,
        #pragma warning restore CS1591
        [EnumMember(Value = "CIF")]
        #pragma warning disable CS1591
        CIF,
        #pragma warning restore CS1591
        [EnumMember(Value = "CIP")]
        #pragma warning disable CS1591
        CIP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPT")]
        #pragma warning disable CS1591
        CPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAF")]
        #pragma warning disable CS1591
        DAF,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAP")]
        #pragma warning disable CS1591
        DAP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAT")]
        #pragma warning disable CS1591
        DAT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DDP")]
        #pragma warning disable CS1591
        DDP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DDU")]
        #pragma warning disable CS1591
        DDU,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEQ")]
        #pragma warning disable CS1591
        DEQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "DES")]
        #pragma warning disable CS1591
        DES,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXW")]
        #pragma warning disable CS1591
        EXW,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAS")]
        #pragma warning disable CS1591
        FAS,
        #pragma warning restore CS1591
        [EnumMember(Value = "FCA")]
        #pragma warning disable CS1591
        FCA,
        #pragma warning restore CS1591
        [EnumMember(Value = "FOB")]
        #pragma warning disable CS1591
        FOB,
        #pragma warning restore CS1591
    }
}
