// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Locations of the nearest Service Center for Dropoff and Pickup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PickupGetServiceCenterFacilitiesResponse_ServiceCenterLocation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The DropOffFacilities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_DropOffFacilities>? DropOffFacilities { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_DropOffFacilities> DropOffFacilities { get; set; }
#endif
        /// <summary>Returns information for Pickup Facilities. This includes name of facility, address, and business hours.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_PickupFacilities? PickupFacilities { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_PickupFacilities PickupFacilities { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.PickupGetServiceCenterFacilitiesResponse_ServiceCenterLocation"/> and sets the default values.
        /// </summary>
        public PickupGetServiceCenterFacilitiesResponse_ServiceCenterLocation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.PickupGetServiceCenterFacilitiesResponse_ServiceCenterLocation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.PickupGetServiceCenterFacilitiesResponse_ServiceCenterLocation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.PickupGetServiceCenterFacilitiesResponse_ServiceCenterLocation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DropOffFacilities", n => { DropOffFacilities = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_DropOffFacilities>(global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_DropOffFacilities.CreateFromDiscriminatorValue)?.AsList(); } },
                { "PickupFacilities", n => { PickupFacilities = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_PickupFacilities>(global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_PickupFacilities.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_DropOffFacilities>("DropOffFacilities", DropOffFacilities);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ServiceCenterLocation_PickupFacilities>("PickupFacilities", PickupFacilities);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
