// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Request to trigger a Smart Pickup (GWN - Green When Needed). This flow applies to accounts enabled for Smart Pickup and supports same-day or future-day pickup requests. Unlike regular Pickup Creation, Smart Pickup does not require a separate Shipper object - it uses the pickup address pre-configured on the UPS account.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PickupTriggerGWNRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>The UPS account number configured for Smart Pickup. Must be a valid 6-character alphanumeric UPS account number associated with the authenticated user. The pickup address and notification preferences are retrieved from this account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Common element for all services</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.PickupCreationRequest_Request? Request { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.PickupCreationRequest_Request Request { get; set; }
#endif
        /// <summary>Specifies when the pickup should be scheduled.- 01 -- Same Day - Request pickup for today - 02 -- Future Day - Request pickup for next available business day  If same-day is requested but cutoff time has passed,the pickup will be automatically scheduled for the next business day. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceDateOption { get; set; }
#nullable restore
#else
        public string ServiceDateOption { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.PickupTriggerGWNRequest"/> and sets the default values.
        /// </summary>
        public PickupTriggerGWNRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.PickupTriggerGWNRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.PickupTriggerGWNRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.PickupTriggerGWNRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountNumber", n => { AccountNumber = n.GetStringValue(); } },
                { "Request", n => { Request = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PickupCreationRequest_Request>(global::Soenneker.Ups.OpenApiClient.Models.PickupCreationRequest_Request.CreateFromDiscriminatorValue); } },
                { "ServiceDateOption", n => { ServiceDateOption = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountNumber", AccountNumber);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PickupCreationRequest_Request>("Request", Request);
            writer.WriteStringValue("ServiceDateOption", ServiceDateOption);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
