// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Comprehensive primary information about the shipment including all tracking details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PrimaryInformation : IAdditionalDataHolder, IParsable
    {
        /// <summary>The actual date and time when the shipment was delivered.</summary>
        public DateTimeOffset? ActualDeliveryDateTime { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of consignee reference numbers associated with the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo>? ConsigneeReferenceNumber { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo> ConsigneeReferenceNumber { get; set; }
#endif
        /// <summary>Contact information for parties involved in the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.ContactInfo>? ContactInfo { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.ContactInfo> ContactInfo { get; set; }
#endif
        /// <summary>Information about containers or packages used in the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.ContainerInfo>? ContainerInformation { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.ContainerInfo> ContainerInformation { get; set; }
#endif
        /// <summary>List of customer purchase order numbers associated with the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo>? CustomerPONumber { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo> CustomerPONumber { get; set; }
#endif
        /// <summary>The name of the destination consignee (party receiving the goods).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationConsignee { get; set; }
#nullable restore
#else
        public string DestinationConsignee { get; set; }
#endif
        /// <summary>List of flight or voyage information for the shipment journey.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.FlightVoyageInfo>? FlightVoyageInformation { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.FlightVoyageInfo> FlightVoyageInformation { get; set; }
#endif
        /// <summary>The unique identifier for the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last known location of the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastKnownLocation { get; set; }
#nullable restore
#else
        public string LastKnownLocation { get; set; }
#endif
        /// <summary>The latest scheduled delivery date and time for the shipment.</summary>
        public DateTimeOffset? LatestScheduledDeliveryDateTime { get; set; }
        /// <summary>Container for shipment milestone information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.Milestone? Milestones { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.Milestone Milestones { get; set; }
#endif
        /// <summary>The current milestone status of the shipment (e.g., In Transit, Delivered).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MilestoneStatus { get; set; }
#nullable restore
#else
        public string MilestoneStatus { get; set; }
#endif
        /// <summary>The code representing the mode of transport.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModeOfTransportCode { get; set; }
#nullable restore
#else
        public string ModeOfTransportCode { get; set; }
#endif
        /// <summary>The name of the mode of transport.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModeOfTransportName { get; set; }
#nullable restore
#else
        public string ModeOfTransportName { get; set; }
#endif
        /// <summary>The original scheduled delivery date and time for the shipment.</summary>
        public DateTimeOffset? OriginalScheduledDeliveryDateTime { get; set; }
        /// <summary>The date and time when the proof of delivery was obtained.</summary>
        public DateTimeOffset? PodDateTime { get; set; }
        /// <summary>The primary exception affecting the shipment, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryException { get; set; }
#nullable restore
#else
        public string PrimaryException { get; set; }
#endif
        /// <summary>The principal party responsible for the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Principal { get; set; }
#nullable restore
#else
        public string Principal { get; set; }
#endif
        /// <summary>The product or service type used for the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Product { get; set; }
#nullable restore
#else
        public string Product { get; set; }
#endif
        /// <summary>The name of the person who received the shipment as proof of delivery.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProofOfDelivery { get; set; }
#nullable restore
#else
        public string ProofOfDelivery { get; set; }
#endif
        /// <summary>List of various reference numbers associated with the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.Reference>? References { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.Reference> References { get; set; }
#endif
        /// <summary>Additional shipment information including weight, volume, and cargo details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.AdditionalInformation? ShipmentAdditionalInformation { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.AdditionalInformation ShipmentAdditionalInformation { get; set; }
#endif
        /// <summary>The date and time when the shipment was booked.</summary>
        public DateTimeOffset? ShipmentBookedDateTime { get; set; }
        /// <summary>The date and time when the shipment was created in the system.</summary>
        public DateTimeOffset? ShipmentCreateDateTime { get; set; }
        /// <summary>Address information for shipment origin or destination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress? ShipmentDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress ShipmentDestination { get; set; }
#endif
        /// <summary>Details about exceptions that occurred during the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.ShipmentExceptionDetails? ShipmentExceptionDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.ShipmentExceptionDetails ShipmentExceptionDetails { get; set; }
#endif
        /// <summary>The date and time of the latest status update for the shipment.</summary>
        public DateTimeOffset? ShipmentLatestStatusDateTime { get; set; }
        /// <summary>The shipment number assigned to this shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipmentNumber { get; set; }
#nullable restore
#else
        public string ShipmentNumber { get; set; }
#endif
        /// <summary>Address information for shipment origin or destination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress? ShipmentOrigin { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress ShipmentOrigin { get; set; }
#endif
        /// <summary>The service level for the shipment (e.g., Express, Standard).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipmentServiceLevel { get; set; }
#nullable restore
#else
        public string ShipmentServiceLevel { get; set; }
#endif
        /// <summary>The type of shipment (e.g., Air, Ocean).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipmentType { get; set; }
#nullable restore
#else
        public string ShipmentType { get; set; }
#endif
        /// <summary>The name of the shipper (party sending the goods).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Shipper { get; set; }
#nullable restore
#else
        public string Shipper { get; set; }
#endif
        /// <summary>The data source system from which the shipment information is retrieved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpsDatasource { get; set; }
#nullable restore
#else
        public string UpsDatasource { get; set; }
#endif
        /// <summary>The UPS file number associated with the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpsFileNumber { get; set; }
#nullable restore
#else
        public string UpsFileNumber { get; set; }
#endif
        /// <summary>The UPS office code handling the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpsOffice { get; set; }
#nullable restore
#else
        public string UpsOffice { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.PrimaryInformation"/> and sets the default values.
        /// </summary>
        public PrimaryInformation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.PrimaryInformation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.PrimaryInformation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.PrimaryInformation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actualDeliveryDateTime", n => { ActualDeliveryDateTime = n.GetDateTimeOffsetValue(); } },
                { "consigneeReferenceNumber", n => { ConsigneeReferenceNumber = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo>(global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contactInfo", n => { ContactInfo = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.ContactInfo>(global::Soenneker.Ups.OpenApiClient.Models.ContactInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "containerInformation", n => { ContainerInformation = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.ContainerInfo>(global::Soenneker.Ups.OpenApiClient.Models.ContainerInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "customerPONumber", n => { CustomerPONumber = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo>(global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "destinationConsignee", n => { DestinationConsignee = n.GetStringValue(); } },
                { "flightVoyageInformation", n => { FlightVoyageInformation = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.FlightVoyageInfo>(global::Soenneker.Ups.OpenApiClient.Models.FlightVoyageInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastKnownLocation", n => { LastKnownLocation = n.GetStringValue(); } },
                { "latestScheduledDeliveryDateTime", n => { LatestScheduledDeliveryDateTime = n.GetDateTimeOffsetValue(); } },
                { "milestoneStatus", n => { MilestoneStatus = n.GetStringValue(); } },
                { "milestones", n => { Milestones = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Milestone>(global::Soenneker.Ups.OpenApiClient.Models.Milestone.CreateFromDiscriminatorValue); } },
                { "modeOfTransportCode", n => { ModeOfTransportCode = n.GetStringValue(); } },
                { "modeOfTransportName", n => { ModeOfTransportName = n.GetStringValue(); } },
                { "originalScheduledDeliveryDateTime", n => { OriginalScheduledDeliveryDateTime = n.GetDateTimeOffsetValue(); } },
                { "podDateTime", n => { PodDateTime = n.GetDateTimeOffsetValue(); } },
                { "primaryException", n => { PrimaryException = n.GetStringValue(); } },
                { "principal", n => { Principal = n.GetStringValue(); } },
                { "product", n => { Product = n.GetStringValue(); } },
                { "proofOfDelivery", n => { ProofOfDelivery = n.GetStringValue(); } },
                { "references", n => { References = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.Reference>(global::Soenneker.Ups.OpenApiClient.Models.Reference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "shipmentAdditionalInformation", n => { ShipmentAdditionalInformation = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.AdditionalInformation>(global::Soenneker.Ups.OpenApiClient.Models.AdditionalInformation.CreateFromDiscriminatorValue); } },
                { "shipmentBookedDateTime", n => { ShipmentBookedDateTime = n.GetDateTimeOffsetValue(); } },
                { "shipmentCreateDateTime", n => { ShipmentCreateDateTime = n.GetDateTimeOffsetValue(); } },
                { "shipmentDestination", n => { ShipmentDestination = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress>(global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress.CreateFromDiscriminatorValue); } },
                { "shipmentExceptionDetails", n => { ShipmentExceptionDetails = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ShipmentExceptionDetails>(global::Soenneker.Ups.OpenApiClient.Models.ShipmentExceptionDetails.CreateFromDiscriminatorValue); } },
                { "shipmentLatestStatusDateTime", n => { ShipmentLatestStatusDateTime = n.GetDateTimeOffsetValue(); } },
                { "shipmentNumber", n => { ShipmentNumber = n.GetStringValue(); } },
                { "shipmentOrigin", n => { ShipmentOrigin = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress>(global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress.CreateFromDiscriminatorValue); } },
                { "shipmentServiceLevel", n => { ShipmentServiceLevel = n.GetStringValue(); } },
                { "shipmentType", n => { ShipmentType = n.GetStringValue(); } },
                { "shipper", n => { Shipper = n.GetStringValue(); } },
                { "upsDatasource", n => { UpsDatasource = n.GetStringValue(); } },
                { "upsFileNumber", n => { UpsFileNumber = n.GetStringValue(); } },
                { "upsOffice", n => { UpsOffice = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("actualDeliveryDateTime", ActualDeliveryDateTime);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo>("consigneeReferenceNumber", ConsigneeReferenceNumber);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.ContactInfo>("contactInfo", ContactInfo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.ContainerInfo>("containerInformation", ContainerInformation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CustomerReferenceInfo>("customerPONumber", CustomerPONumber);
            writer.WriteStringValue("destinationConsignee", DestinationConsignee);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.FlightVoyageInfo>("flightVoyageInformation", FlightVoyageInformation);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("lastKnownLocation", LastKnownLocation);
            writer.WriteDateTimeOffsetValue("latestScheduledDeliveryDateTime", LatestScheduledDeliveryDateTime);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.Milestone>("milestones", Milestones);
            writer.WriteStringValue("milestoneStatus", MilestoneStatus);
            writer.WriteStringValue("modeOfTransportCode", ModeOfTransportCode);
            writer.WriteStringValue("modeOfTransportName", ModeOfTransportName);
            writer.WriteDateTimeOffsetValue("originalScheduledDeliveryDateTime", OriginalScheduledDeliveryDateTime);
            writer.WriteDateTimeOffsetValue("podDateTime", PodDateTime);
            writer.WriteStringValue("primaryException", PrimaryException);
            writer.WriteStringValue("principal", Principal);
            writer.WriteStringValue("product", Product);
            writer.WriteStringValue("proofOfDelivery", ProofOfDelivery);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.Reference>("references", References);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.AdditionalInformation>("shipmentAdditionalInformation", ShipmentAdditionalInformation);
            writer.WriteDateTimeOffsetValue("shipmentBookedDateTime", ShipmentBookedDateTime);
            writer.WriteDateTimeOffsetValue("shipmentCreateDateTime", ShipmentCreateDateTime);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress>("shipmentDestination", ShipmentDestination);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ShipmentExceptionDetails>("shipmentExceptionDetails", ShipmentExceptionDetails);
            writer.WriteDateTimeOffsetValue("shipmentLatestStatusDateTime", ShipmentLatestStatusDateTime);
            writer.WriteStringValue("shipmentNumber", ShipmentNumber);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.ShipmentAddress>("shipmentOrigin", ShipmentOrigin);
            writer.WriteStringValue("shipmentServiceLevel", ShipmentServiceLevel);
            writer.WriteStringValue("shipmentType", ShipmentType);
            writer.WriteStringValue("shipper", Shipper);
            writer.WriteStringValue("upsDatasource", UpsDatasource);
            writer.WriteStringValue("upsFileNumber", UpsFileNumber);
            writer.WriteStringValue("upsOffice", UpsOffice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
