// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QuantumViewSubscriptionFileGeneric : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Information about package activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericActivity? Activity { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericActivity Activity { get; set; }
#endif
        /// <summary>Unique identifier that defines the type of activity. - VM = Void for Manifest- UR = Undeliverable Returns- IR = Invoice Removal Successful- TC = Transport Company USPS scan PS = &apos;Postal Service Possession Scan&apos;- FN = UPS Access Point/Alternate Delivery Location Email Notification Failure- DS = Destination Scan- AG = Package is in transit to a UPS facility- RE = UPS Returns Exchange - RP = Retail Pickup- UD = Updated delivery date- OD = Out for Delivery- SD = Scheduled for Delivery- FM = Tendered to FMP- PT = UPS Courier Handoff (Package Tendered) DIALS -VX- PC = UPS Courier Confirmation – XPLD -VX- OT = Out For Delivery Today scan- AD = At Delivery Site scan- RO = Roadie Out for Delivery</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivityType { get; set; }
#nullable restore
#else
        public string ActivityType { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The information provided within this container identifies the shipper number and billing option the user specified to view during the subscription process.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericBillToAccount? BillToAccount { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericBillToAccount BillToAccount { get; set; }
#endif
        /// <summary>Failure notification information containing email address and Notification code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericFailureNotification? FailureNotification { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericFailureNotification FailureNotification { get; set; }
#endif
        /// <summary>Package-level reference number.**NOTE:** For versions &gt;= v3, this element will always be returned as an array. For requests using version = v1 and v2, this element will be returned as an array if there is more than one object and a single object if there is only 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericPackageReferenceNumber>? PackageReferenceNumber { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericPackageReferenceNumber> PackageReferenceNumber { get; set; }
#endif
        /// <summary>If Activity Type is &quot;DS&quot; or &quot;UD&quot;, this element will contain Rescheduled Delivery Date. Format will be YYYYMMDD.If Activity Type is &quot;OD&quot;, this element will contain Rescheduled Delivery Date. Format will be YYYYMMDD.If Activity Type is &quot;SD&quot;, this element will contain agreed upon date with Customer for delivery Date. Format will be YYYYMMDD.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RescheduledDeliveryDate { get; set; }
#nullable restore
#else
        public string RescheduledDeliveryDate { get; set; }
#endif
        /// <summary>Container for service code and description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericService? Service { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericService Service { get; set; }
#endif
        /// <summary>Container tag for shipment reference number.**NOTE:** For versions &gt;= v3, this element will always be returned as an array. For requests using version = v1 and v2, this element will be returned as an array if there is more than one object and a single object if there is only 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipmentReferenceNumber>? ShipmentReferenceNumber { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipmentReferenceNumber> ShipmentReferenceNumber { get; set; }
#endif
        /// <summary>Shipper&apos;s alphanumeric account number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipperNumber { get; set; }
#nullable restore
#else
        public string ShipperNumber { get; set; }
#endif
        /// <summary>Address and contact information describing the location where a return is to be delivered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipTo? ShipTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipTo ShipTo { get; set; }
#endif
        /// <summary>Package&apos;s tracking number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackingNumber { get; set; }
#nullable restore
#else
        public string TrackingNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.QuantumViewSubscriptionFileGeneric"/> and sets the default values.
        /// </summary>
        public QuantumViewSubscriptionFileGeneric()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.QuantumViewSubscriptionFileGeneric"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.QuantumViewSubscriptionFileGeneric CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.QuantumViewSubscriptionFileGeneric();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Activity", n => { Activity = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericActivity>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericActivity.CreateFromDiscriminatorValue); } },
                { "ActivityType", n => { ActivityType = n.GetStringValue(); } },
                { "BillToAccount", n => { BillToAccount = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericBillToAccount>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericBillToAccount.CreateFromDiscriminatorValue); } },
                { "FailureNotification", n => { FailureNotification = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericFailureNotification>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericFailureNotification.CreateFromDiscriminatorValue); } },
                { "PackageReferenceNumber", n => { PackageReferenceNumber = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericPackageReferenceNumber>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericPackageReferenceNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "RescheduledDeliveryDate", n => { RescheduledDeliveryDate = n.GetStringValue(); } },
                { "Service", n => { Service = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericService>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericService.CreateFromDiscriminatorValue); } },
                { "ShipTo", n => { ShipTo = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipTo>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipTo.CreateFromDiscriminatorValue); } },
                { "ShipmentReferenceNumber", n => { ShipmentReferenceNumber = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipmentReferenceNumber>(global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipmentReferenceNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ShipperNumber", n => { ShipperNumber = n.GetStringValue(); } },
                { "TrackingNumber", n => { TrackingNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericActivity>("Activity", Activity);
            writer.WriteStringValue("ActivityType", ActivityType);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericBillToAccount>("BillToAccount", BillToAccount);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericFailureNotification>("FailureNotification", FailureNotification);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericPackageReferenceNumber>("PackageReferenceNumber", PackageReferenceNumber);
            writer.WriteStringValue("RescheduledDeliveryDate", RescheduledDeliveryDate);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericService>("Service", Service);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipmentReferenceNumber>("ShipmentReferenceNumber", ShipmentReferenceNumber);
            writer.WriteStringValue("ShipperNumber", ShipperNumber);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.QuantumViewGenericShipTo>("ShipTo", ShipTo);
            writer.WriteStringValue("TrackingNumber", TrackingNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
