// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QuoteShipmentDetails : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The airCargoItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.AirCargoItem>? AirCargoItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.AirCargoItem> AirCargoItems { get; set; }
#endif
        /// <summary>The commodityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommodityName { get; set; }
#nullable restore
#else
        public string CommodityName { get; set; }
#endif
        /// <summary>The customsValue property</summary>
        public double? CustomsValue { get; set; }
        /// <summary>The customsValueCurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomsValueCurrency { get; set; }
#nullable restore
#else
        public string CustomsValueCurrency { get; set; }
#endif
        /// <summary>The fclCargoItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.CargoItem>? FclCargoItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.CargoItem> FclCargoItems { get; set; }
#endif
        /// <summary>The insuredValue property</summary>
        public double? InsuredValue { get; set; }
        /// <summary>The insuredValueCurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InsuredValueCurrency { get; set; }
#nullable restore
#else
        public string InsuredValueCurrency { get; set; }
#endif
        /// <summary>The lclCargoItems property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.LclCargoItem>? LclCargoItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.LclCargoItem> LclCargoItems { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Ups.OpenApiClient.Models.Location>? Location { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Ups.OpenApiClient.Models.Location> Location { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.QuoteShipmentDetails"/> and sets the default values.
        /// </summary>
        public QuoteShipmentDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.QuoteShipmentDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.QuoteShipmentDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.QuoteShipmentDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "airCargoItems", n => { AirCargoItems = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.AirCargoItem>(global::Soenneker.Ups.OpenApiClient.Models.AirCargoItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commodityName", n => { CommodityName = n.GetStringValue(); } },
                { "customsValue", n => { CustomsValue = n.GetDoubleValue(); } },
                { "customsValueCurrency", n => { CustomsValueCurrency = n.GetStringValue(); } },
                { "fclCargoItems", n => { FclCargoItems = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CargoItem>(global::Soenneker.Ups.OpenApiClient.Models.CargoItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "insuredValue", n => { InsuredValue = n.GetDoubleValue(); } },
                { "insuredValueCurrency", n => { InsuredValueCurrency = n.GetStringValue(); } },
                { "lclCargoItems", n => { LclCargoItems = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.LclCargoItem>(global::Soenneker.Ups.OpenApiClient.Models.LclCargoItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "location", n => { Location = n.GetCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.Location>(global::Soenneker.Ups.OpenApiClient.Models.Location.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.AirCargoItem>("airCargoItems", AirCargoItems);
            writer.WriteStringValue("commodityName", CommodityName);
            writer.WriteDoubleValue("customsValue", CustomsValue);
            writer.WriteStringValue("customsValueCurrency", CustomsValueCurrency);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.CargoItem>("fclCargoItems", FclCargoItems);
            writer.WriteDoubleValue("insuredValue", InsuredValue);
            writer.WriteStringValue("insuredValueCurrency", InsuredValueCurrency);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.LclCargoItem>("lclCargoItems", LclCargoItems);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Ups.OpenApiClient.Models.Location>("location", Location);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
