// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Detailed charges.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RateResultChargeDetail : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Monetary value of the charge.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeAmount { get; set; }
#nullable restore
#else
        public string ChargeAmount { get; set; }
#endif
        /// <summary>Indicates the general charge type- A = ACCESSORIAL TYPE- B = BASE CHARGE TYPE- S = SURCHARGE TYPE</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeCode { get; set; }
#nullable restore
#else
        public string ChargeCode { get; set; }
#endif
        /// <summary>Description of each charge.The possible descriptions are:- BASE CHARGE- EXTENDED AREA SURCHARGE- FUEL SURCHARGE- REMOTE AREA SURCHARGE- RESIDENTIAL SURCHARGE- SATURDAY ON-CALL STOP CHARGE</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeDescription { get; set; }
#nullable restore
#else
        public string ChargeDescription { get; set; }
#endif
        /// <summary>Monetary value of the incented charge. Only present if 1. UserLevelDiscountIndicator = Y and User Level Promotion is applied to the pickup or 2 .if any incentive rate is applied to the pickup and SubVersion on the request is greater than or equal to 1707.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncentedAmount { get; set; }
#nullable restore
#else
        public string IncentedAmount { get; set; }
#endif
        /// <summary>Monetary value of the tax if apply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxAmount { get; set; }
#nullable restore
#else
        public string TaxAmount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.RateResultChargeDetail"/> and sets the default values.
        /// </summary>
        public RateResultChargeDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.RateResultChargeDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.RateResultChargeDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.RateResultChargeDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ChargeAmount", n => { ChargeAmount = n.GetStringValue(); } },
                { "ChargeCode", n => { ChargeCode = n.GetStringValue(); } },
                { "ChargeDescription", n => { ChargeDescription = n.GetStringValue(); } },
                { "IncentedAmount", n => { IncentedAmount = n.GetStringValue(); } },
                { "TaxAmount", n => { TaxAmount = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ChargeAmount", ChargeAmount);
            writer.WriteStringValue("ChargeCode", ChargeCode);
            writer.WriteStringValue("ChargeDescription", ChargeDescription);
            writer.WriteStringValue("IncentedAmount", IncentedAmount);
            writer.WriteStringValue("TaxAmount", TaxAmount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
