// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// Package Container.  Only one Package allowed for Simple Rate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RatingShipmentPackage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A flag indicating if the packages require additional handling. True if AdditionalHandlingIndicator tag exists; false otherwise. Additional Handling indicator indicates it&apos;s a non-corrugated package.  Empty Tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalHandlingIndicator { get; set; }
#nullable restore
#else
        public string AdditionalHandlingIndicator { get; set; }
#endif
        /// <summary>Commodity Container.  Required only for GFP rating when FRSShipmentIndicator is requested.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.PackageCommodity? Commodity { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.PackageCommodity Commodity { get; set; }
#endif
        /// <summary>Dimensions Container. This container is not applicable for GFP Rating request.  Required for Heavy Goods service. Package Dimension will be ignored for Simple Rate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.RatingPackageDimensions? Dimensions { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.RatingPackageDimensions Dimensions { get; set; }
#endif
        /// <summary>Package Dimensional Weight container. Values in this container are ignored when package dimensions are provided. Please visit ups.com for instructions on calculating this value.  Only used for non-US/CA/PR shipments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.PackageDimWeight? DimWeight { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.PackageDimWeight DimWeight { get; set; }
#endif
        /// <summary>This element does not require a value and if one is entered it will be ignored.  If present, it indicates the shipment will be categorized as a Large Package.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LargePackageIndicator { get; set; }
#nullable restore
#else
        public string LargePackageIndicator { get; set; }
#endif
        /// <summary>Presence/Absence Indicator. Any value inside is ignored. It indicates if packge is qualified for minimum billable weight.  Applicable for UPS Worldwide Economy DDU service</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MinimumBillableWeightIndicator { get; set; }
#nullable restore
#else
        public string MinimumBillableWeightIndicator { get; set; }
#endif
        /// <summary>Presence/Absence Indicator. Any value inside is ignored. It indicates if packge is oversized.  Applicable for UPS Worldwide Economy DDU service</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OversizeIndicator { get; set; }
#nullable restore
#else
        public string OversizeIndicator { get; set; }
#endif
        /// <summary>PackageServiceOptions container.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageServiceOptions? PackageServiceOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageServiceOptions PackageServiceOptions { get; set; }
#endif
        /// <summary>Package Weight Container.  Required for an GFP Rating request. Otherwise optional. Required for Heavy Goods service.  Package Weight will be ignored for Simple Rate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageWeight? PackageWeight { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageWeight PackageWeight { get; set; }
#endif
        /// <summary>Packaging Type Container.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.PackagePackagingType? PackagingType { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.PackagePackagingType PackagingType { get; set; }
#endif
        /// <summary>SimpleRate Container</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.PackageSimpleRate? SimpleRate { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.PackageSimpleRate SimpleRate { get; set; }
#endif
        /// <summary>UPS Premier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.PackageUPSPremier? UPSPremier { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.PackageUPSPremier UPSPremier { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.RatingShipmentPackage"/> and sets the default values.
        /// </summary>
        public RatingShipmentPackage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.RatingShipmentPackage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.RatingShipmentPackage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.RatingShipmentPackage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AdditionalHandlingIndicator", n => { AdditionalHandlingIndicator = n.GetStringValue(); } },
                { "Commodity", n => { Commodity = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageCommodity>(global::Soenneker.Ups.OpenApiClient.Models.PackageCommodity.CreateFromDiscriminatorValue); } },
                { "DimWeight", n => { DimWeight = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageDimWeight>(global::Soenneker.Ups.OpenApiClient.Models.PackageDimWeight.CreateFromDiscriminatorValue); } },
                { "Dimensions", n => { Dimensions = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.RatingPackageDimensions>(global::Soenneker.Ups.OpenApiClient.Models.RatingPackageDimensions.CreateFromDiscriminatorValue); } },
                { "LargePackageIndicator", n => { LargePackageIndicator = n.GetStringValue(); } },
                { "MinimumBillableWeightIndicator", n => { MinimumBillableWeightIndicator = n.GetStringValue(); } },
                { "OversizeIndicator", n => { OversizeIndicator = n.GetStringValue(); } },
                { "PackageServiceOptions", n => { PackageServiceOptions = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageServiceOptions>(global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageServiceOptions.CreateFromDiscriminatorValue); } },
                { "PackageWeight", n => { PackageWeight = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageWeight>(global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageWeight.CreateFromDiscriminatorValue); } },
                { "PackagingType", n => { PackagingType = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackagePackagingType>(global::Soenneker.Ups.OpenApiClient.Models.PackagePackagingType.CreateFromDiscriminatorValue); } },
                { "SimpleRate", n => { SimpleRate = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageSimpleRate>(global::Soenneker.Ups.OpenApiClient.Models.PackageSimpleRate.CreateFromDiscriminatorValue); } },
                { "UPSPremier", n => { UPSPremier = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageUPSPremier>(global::Soenneker.Ups.OpenApiClient.Models.PackageUPSPremier.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AdditionalHandlingIndicator", AdditionalHandlingIndicator);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageCommodity>("Commodity", Commodity);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.RatingPackageDimensions>("Dimensions", Dimensions);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageDimWeight>("DimWeight", DimWeight);
            writer.WriteStringValue("LargePackageIndicator", LargePackageIndicator);
            writer.WriteStringValue("MinimumBillableWeightIndicator", MinimumBillableWeightIndicator);
            writer.WriteStringValue("OversizeIndicator", OversizeIndicator);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageServiceOptions>("PackageServiceOptions", PackageServiceOptions);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.RatingPackagePackageWeight>("PackageWeight", PackageWeight);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackagePackagingType>("PackagingType", PackagingType);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageSimpleRate>("SimpleRate", SimpleRate);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.PackageUPSPremier>("UPSPremier", UPSPremier);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
