// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchResults_GeocodeCandidate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Contains all of the basic information about candidate address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_AddressKeyFormat? AddressKeyFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_AddressKeyFormat AddressKeyFormat { get; set; }
#endif
        /// <summary>Geocode is the latitude and longitude of the origin candidate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_Geocode? Geocode { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_Geocode Geocode { get; set; }
#endif
        /// <summary>If a Landmark code was provided in the request, a candidate list of Landmark Names will be returned along with the corresponding address and Geocode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LandmarkName { get; set; }
#nullable restore
#else
        public string LandmarkName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.SearchResults_GeocodeCandidate"/> and sets the default values.
        /// </summary>
        public SearchResults_GeocodeCandidate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.SearchResults_GeocodeCandidate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.SearchResults_GeocodeCandidate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.SearchResults_GeocodeCandidate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddressKeyFormat", n => { AddressKeyFormat = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_AddressKeyFormat>(global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_AddressKeyFormat.CreateFromDiscriminatorValue); } },
                { "Geocode", n => { Geocode = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_Geocode>(global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_Geocode.CreateFromDiscriminatorValue); } },
                { "LandmarkName", n => { LandmarkName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_AddressKeyFormat>("AddressKeyFormat", AddressKeyFormat);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.GeocodeCandidate_Geocode>("Geocode", Geocode);
            writer.WriteStringValue("LandmarkName", LandmarkName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
