// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// The SmartPickup request container
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmartPickupRequestV1SmartPickupRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>The UPS account information that you want to use for SmartPickupTrigger and NotificationIndicator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAccountInfo? AccountInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAccountInfo AccountInfo { get; set; }
#endif
        /// <summary>Action indicator to decide the flow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAction? Action { get; set; }
#nullable restore
#else
        public global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAction Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Notification opt-out - a CTA/link on the transactional PU alert that takes the User to a unique landing page(determined by whether the User/Email combo have a ups.com User ID or not) so that they can opt-out of receivingthese transactional alerts for this account. Required when Action is Add or Update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotificationIndicator { get; set; }
#nullable restore
#else
        public string NotificationIndicator { get; set; }
#endif
        /// <summary>Smart pickup trigger when the PU event (PRN) for the Smart PU is moved from pending to scheduled. Required when Action is Add or Updtae.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmartPickupTrigger { get; set; }
#nullable restore
#else
        public string SmartPickupTrigger { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequest"/> and sets the default values.
        /// </summary>
        public SmartPickupRequestV1SmartPickupRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountInfo", n => { AccountInfo = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAccountInfo>(global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAccountInfo.CreateFromDiscriminatorValue); } },
                { "Action", n => { Action = n.GetObjectValue<global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAction>(global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAction.CreateFromDiscriminatorValue); } },
                { "NotificationIndicator", n => { NotificationIndicator = n.GetStringValue(); } },
                { "SmartPickupTrigger", n => { SmartPickupTrigger = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAccountInfo>("AccountInfo", AccountInfo);
            writer.WriteObjectValue<global::Soenneker.Ups.OpenApiClient.Models.SmartPickupRequestV1SmartPickupRequestAction>("Action", Action);
            writer.WriteStringValue("NotificationIndicator", NotificationIndicator);
            writer.WriteStringValue("SmartPickupTrigger", SmartPickupTrigger);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
