// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>Indicates if the pickup address qualifies for WST (Weekend Service Territory) pickup. Available when PickupTypeCode is **02** and pickup address is WST area. </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SmartPickupPickupInfoV1WeekendServiceTerritoryIndicator
    {
        [EnumMember(Value = "N")]
        #pragma warning disable CS1591
        N,
        #pragma warning restore CS1591
        [EnumMember(Value = "Y")]
        #pragma warning disable CS1591
        Y,
        #pragma warning restore CS1591
    }
}
