// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>Temperature unit of measurement</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TemperatureTemperatureUom
    {
        [EnumMember(Value = "C")]
        #pragma warning disable CS1591
        C,
        #pragma warning restore CS1591
        [EnumMember(Value = "F")]
        #pragma warning disable CS1591
        F,
        #pragma warning restore CS1591
    }
}
