// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>
    /// N/A
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimeInTransitRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Used to bypass address validation when the address has already been validated by the calling application.    Valid values: true, false   Defaults to true  Note: not to be exposed to external customers.&quot;</summary>
        public bool? AvvFlag { get; set; }
        /// <summary>&quot;Required for International Requests.  Valid values: \&quot;02\&quot;,\&quot;03\&quot;,\&quot;04\&quot;  02 - Document  03 - Non Document  04 - WWEF (Pallet)&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillType { get; set; }
#nullable restore
#else
        public string BillType { get; set; }
#endif
        /// <summary>The shipment destination city. Required for International Requests for those countries that do not utilize postal codes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationCityName { get; set; }
#nullable restore
#else
        public string DestinationCityName { get; set; }
#endif
        /// <summary>&quot;The country code of the destination.   Valid values:  Must conform to ISO-defined country codes.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationCountryCode { get; set; }
#nullable restore
#else
        public string DestinationCountryCode { get; set; }
#endif
        /// <summary>The shipment destination postal code.   Required for Domestic requests. Either 5, or 9-digit U.S. zip codes must be used for U.S. addresses.  For non-U.S. addresses, this is recommended for all countries that utilize postal codes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationPostalCode { get; set; }
#nullable restore
#else
        public string DestinationPostalCode { get; set; }
#endif
        /// <summary>The shipment destination state or province.  For U.S. addresses, the value must be a valid 2-character value (per U.S. Mail standards).   For non-U.S. addresses the full State or Province name should be provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationStateProvince { get; set; }
#nullable restore
#else
        public string DestinationStateProvince { get; set; }
#endif
        /// <summary>The shipment destination town.  Town is a subdivision of city.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationTownName { get; set; }
#nullable restore
#else
        public string DestinationTownName { get; set; }
#endif
        /// <summary>&quot;Sets the indicator for an international Freight Pallet shipment that is going to be dropped off by shipper to a UPS facility.  The indicator is used when the Bill Type is \&quot;04\&quot;.    Valid values: \&quot;0\&quot;, \&quot;1\&quot;.   0 = WWDTProcessIF.PICKUP_BY_UPS  1 = WWDTProcessIf.DROPOFF_BY_SHIPPER   The default value is \&quot;0\&quot; &quot;</summary>
        public int? DropOffAtFacilityIndicator { get; set; }
        /// <summary>&quot;Sets the indicator for an international Freight Pallet shipment that is going to be pick-up by consignee in a destination facility.  The indicator is used when the Bill Type is \&quot;04\&quot;.    Valid values: \&quot;0\&quot;, \&quot;1\&quot;.   0 = WWDTProcessIF.DELIVERY_BY_UPS  1 = WWDTProcessIf.PICKUP_BY_CONSIGNEE   The default value is \&quot;0\&quot; &quot;</summary>
        public int? HoldForPickupIndicator { get; set; }
        /// <summary>Sets the limit for the number of candidates returned in candidate list.    Default value is 200.</summary>
        public int? MaxList { get; set; }
        /// <summary>Sets the number of packages in shipment.  Default value is 1.</summary>
        public int? NumberOfPackages { get; set; }
        /// <summary>The shipment origin city. Required for International requests for those countries that do not utilize postal codes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginCityName { get; set; }
#nullable restore
#else
        public string OriginCityName { get; set; }
#endif
        /// <summary>&quot;The country code of the origin shipment. Valid Values: Must conform to the ISO-defined, two-letter country or territory codes.  Refer to Country or Territory Codes in the Appendix above for valid values.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginCountryCode { get; set; }
#nullable restore
#else
        public string OriginCountryCode { get; set; }
#endif
        /// <summary>Required for Domestic requests.  The shipment origin postal code.  Either the 5, or 9-digit US zip codes must be used for U.S. addresses.  For non-U.S. addresses, this is recommended for all countries that utilize postal codes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginPostalCode { get; set; }
#nullable restore
#else
        public string OriginPostalCode { get; set; }
#endif
        /// <summary>The shipment origin state or province.  For U.S. addresses, the value must be a valid 2-character value (per U.S. Mail standards)  For non-U.S. addresses the full State or Province name should be provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginStateProvince { get; set; }
#nullable restore
#else
        public string OriginStateProvince { get; set; }
#endif
        /// <summary>The shipment origin town. Town is a subdivision of city.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginTownName { get; set; }
#nullable restore
#else
        public string OriginTownName { get; set; }
#endif
        /// <summary>&quot;Sets the indicator for premier time in transit when the shipment contains a premier package.   Valid values: “00”, “01”.    00 = Non-premier time in transit.   01 = Premier time in transit.    The default value is “00”.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PremierIndicator { get; set; }
#nullable restore
#else
        public string PremierIndicator { get; set; }
#endif
        /// <summary>&quot;Indicates if address is residential or commercial. Required for Domestic requests.   Valid values: \&quot;01\&quot;, \&quot;02\&quot;   01 = Residential  02 = Commercial   Defaults to commercial for International Requests.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResidentialIndicator { get; set; }
#nullable restore
#else
        public string ResidentialIndicator { get; set; }
#endif
        /// <summary>Used to get back a full list of services - bypassing current WWDT business rules to remove services from the list being returned to clients for US domestic that are slower than UPS Ground.    Default value is false.</summary>
        public bool? ReturnUnfilterdServices { get; set; }
        /// <summary>The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up by UPS).  Allowed range is up to 60 days in future and 35 days in past. This date may or may not be the UPS business date. Format is YYYY-MM-DD.  YYYY = 4 digit year; MM = 2 digit month, valid values 01-12; DD = 2 digit day of month, valid values 01-31  If no value is provided, defaults to current system date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipDate { get; set; }
#nullable restore
#else
        public string ShipDate { get; set; }
#endif
        /// <summary>&quot;The unit of currency used for values. Required if ShipmentContentsValue is populated.  Valid value: must conform to ISO standards.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipmentContentsCurrencyCode { get; set; }
#nullable restore
#else
        public string ShipmentContentsCurrencyCode { get; set; }
#endif
        /// <summary>&quot;The monetary value of shipment contents.   Required when origin country does not equal destination country and BillType is 03 (non-documented) or 04 (WWEF)   Required when origin country does not equal destination country, and destination country = CA, and BillType = 02 (document).   Note: If decimal values are used, valid values will be rounded to the tenths.&quot;</summary>
        public double? ShipmentContentsValue { get; set; }
        /// <summary>The time the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up by UPS).   Format is HH:MM:SS  Defaults to current time if not provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShipTime { get; set; }
#nullable restore
#else
        public string ShipTime { get; set; }
#endif
        /// <summary>&quot;The weight of the shipment. Required for International requests.   Note: If decimal values are used, valid values will be rounded to the tenths.    Note: Maximum value is 70 kilograms or 150 pounds.&quot;</summary>
        public double? Weight { get; set; }
        /// <summary>&quot;Required for International requests and when weight value is provided.   Valid Values: \&quot;LBS\&quot;, \&quot;KGS\&quot;&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WeightUnitOfMeasure { get; set; }
#nullable restore
#else
        public string WeightUnitOfMeasure { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Models.TimeInTransitRequest"/> and sets the default values.
        /// </summary>
        public TimeInTransitRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.TimeInTransitRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Ups.OpenApiClient.Models.TimeInTransitRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Ups.OpenApiClient.Models.TimeInTransitRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avvFlag", n => { AvvFlag = n.GetBoolValue(); } },
                { "billType", n => { BillType = n.GetStringValue(); } },
                { "destinationCityName", n => { DestinationCityName = n.GetStringValue(); } },
                { "destinationCountryCode", n => { DestinationCountryCode = n.GetStringValue(); } },
                { "destinationPostalCode", n => { DestinationPostalCode = n.GetStringValue(); } },
                { "destinationStateProvince", n => { DestinationStateProvince = n.GetStringValue(); } },
                { "destinationTownName", n => { DestinationTownName = n.GetStringValue(); } },
                { "dropOffAtFacilityIndicator", n => { DropOffAtFacilityIndicator = n.GetIntValue(); } },
                { "holdForPickupIndicator", n => { HoldForPickupIndicator = n.GetIntValue(); } },
                { "maxList", n => { MaxList = n.GetIntValue(); } },
                { "numberOfPackages", n => { NumberOfPackages = n.GetIntValue(); } },
                { "originCityName", n => { OriginCityName = n.GetStringValue(); } },
                { "originCountryCode", n => { OriginCountryCode = n.GetStringValue(); } },
                { "originPostalCode", n => { OriginPostalCode = n.GetStringValue(); } },
                { "originStateProvince", n => { OriginStateProvince = n.GetStringValue(); } },
                { "originTownName", n => { OriginTownName = n.GetStringValue(); } },
                { "premierIndicator", n => { PremierIndicator = n.GetStringValue(); } },
                { "residentialIndicator", n => { ResidentialIndicator = n.GetStringValue(); } },
                { "returnUnfilterdServices", n => { ReturnUnfilterdServices = n.GetBoolValue(); } },
                { "shipDate", n => { ShipDate = n.GetStringValue(); } },
                { "shipTime", n => { ShipTime = n.GetStringValue(); } },
                { "shipmentContentsCurrencyCode", n => { ShipmentContentsCurrencyCode = n.GetStringValue(); } },
                { "shipmentContentsValue", n => { ShipmentContentsValue = n.GetDoubleValue(); } },
                { "weight", n => { Weight = n.GetDoubleValue(); } },
                { "weightUnitOfMeasure", n => { WeightUnitOfMeasure = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("avvFlag", AvvFlag);
            writer.WriteStringValue("billType", BillType);
            writer.WriteStringValue("destinationCityName", DestinationCityName);
            writer.WriteStringValue("destinationCountryCode", DestinationCountryCode);
            writer.WriteStringValue("destinationPostalCode", DestinationPostalCode);
            writer.WriteStringValue("destinationStateProvince", DestinationStateProvince);
            writer.WriteStringValue("destinationTownName", DestinationTownName);
            writer.WriteIntValue("dropOffAtFacilityIndicator", DropOffAtFacilityIndicator);
            writer.WriteIntValue("holdForPickupIndicator", HoldForPickupIndicator);
            writer.WriteIntValue("maxList", MaxList);
            writer.WriteIntValue("numberOfPackages", NumberOfPackages);
            writer.WriteStringValue("originCityName", OriginCityName);
            writer.WriteStringValue("originCountryCode", OriginCountryCode);
            writer.WriteStringValue("originPostalCode", OriginPostalCode);
            writer.WriteStringValue("originStateProvince", OriginStateProvince);
            writer.WriteStringValue("originTownName", OriginTownName);
            writer.WriteStringValue("premierIndicator", PremierIndicator);
            writer.WriteStringValue("residentialIndicator", ResidentialIndicator);
            writer.WriteBoolValue("returnUnfilterdServices", ReturnUnfilterdServices);
            writer.WriteStringValue("shipDate", ShipDate);
            writer.WriteStringValue("shipmentContentsCurrencyCode", ShipmentContentsCurrencyCode);
            writer.WriteDoubleValue("shipmentContentsValue", ShipmentContentsValue);
            writer.WriteStringValue("shipTime", ShipTime);
            writer.WriteDoubleValue("weight", Weight);
            writer.WriteStringValue("weightUnitOfMeasure", WeightUnitOfMeasure);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
