// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>The media type code for the notification.Valid values are:- 03 = Email- 04 = Fax</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TradeDirectNotificationBeforeDeliveryMediaTypeCode
    {
        [EnumMember(Value = "03")]
        #pragma warning disable CS1591
        Value03,
        #pragma warning restore CS1591
        [EnumMember(Value = "04")]
        #pragma warning disable CS1591
        Value04,
        #pragma warning restore CS1591
    }
}
