// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>Shipment type. | Supported enum values                                                                                || :--------------------------------------------------------------------------------------------------- || `GIFT`&lt;br&gt;Items sent as gifts, typically for personal reasons.                                       || `COMM`&lt;br&gt;Commercial goods or commodities, usually for business transactions. Sale, sample, repair.  || `OTHR`&lt;br&gt;Return, Other, and Intercompany Data, Anything else not supported.                         || `PERS`&lt;br&gt;Personal items, often for relocation or personal use                                       |</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpsExportAssureShipmentRequestShipmentType
    {
        [EnumMember(Value = "GIFT")]
        #pragma warning disable CS1591
        Gift,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMM")]
        #pragma warning disable CS1591
        Comm,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHR")]
        #pragma warning disable CS1591
        Othr,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERS")]
        #pragma warning disable CS1591
        Pers,
        #pragma warning restore CS1591
    }
}
