// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Ups.OpenApiClient.Models
{
    /// <summary>Gross weight unit. Only required if there is a value for `grossWeight`; If `grossWeight` is not specified, this value must equal `null`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpsExportAssureShipmentRequestGrossWeightUnit
    {
        [EnumMember(Value = "KG")]
        #pragma warning disable CS1591
        Kg,
        #pragma warning restore CS1591
        [EnumMember(Value = "LB")]
        #pragma warning disable CS1591
        Lb,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
