// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Forwarding.Shipments.Milestones;
using Soenneker.Ups.OpenApiClient.Forwarding.Shipments.Rates;
using Soenneker.Ups.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.Forwarding.Shipments
{
    /// <summary>
    /// Builds and executes requests for operations under \Forwarding\shipments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShipmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The milestones property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.Milestones.MilestonesRequestBuilder Milestones
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.Milestones.MilestonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rates property</summary>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.Rates.RatesRequestBuilder Rates
        {
            get => new global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.Rates.RatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShipmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Forwarding/shipments?request_type={request_type}&shipment_id={shipment_id}&shipper_account_number={shipper_account_number}{&manifest_format*,pickup_date*,request_manifest*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShipmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Forwarding/shipments?request_type={request_type}&shipment_id={shipment_id}&shipper_account_number={shipper_account_number}{&manifest_format*,pickup_date*,request_manifest*}", rawUrl)
        {
        }
        /// <summary>
        /// Cancels a shipment using the provided shipment number and shipper&apos;s UPS Freight Account Number.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelResponseV1"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelResponseV1?> DeleteAsync(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelResponseV1> DeleteAsync(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelResponseV1>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelResponseV1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves shipment details for air or ocean quotes based on the specified request parameters.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloShipmentDetailResponseV1"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloShipmentDetailResponseV1?> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloShipmentDetailResponseV1> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.ApolloShipmentDetailResponseV1>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.ApolloShipmentDetailResponseV1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Processes all shipments created for a specific shipper during the day and returns a manifest.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentDataResponseV1"/></returns>
        /// <param name="body">The unbounded list of objects to change with their values</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentDataResponseV1?> PatchAsync(List<global::Soenneker.Ups.OpenApiClient.Models.ApolloPatchReplaceReqV1_item> body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentDataResponseV1> PatchAsync(List<global::Soenneker.Ups.OpenApiClient.Models.ApolloPatchReplaceReqV1_item> body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentDataResponseV1>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentDataResponseV1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Generate estimated freight rates based on the provided shipment and party details, and create the shipment.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipResponseV1"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipResponseV1?> PostAsync(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipResponseV1> PostAsync(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipResponseV1>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipResponseV1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Cancels a shipment using the provided shipment number and shipper&apos;s UPS Freight Account Number.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipmentCancelRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, "{+baseurl}/Forwarding/shipments", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Retrieves shipment details for air or ocean quotes based on the specified request parameters.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/Forwarding/shipments?request_type={request_type}&shipment_id={shipment_id}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Processes all shipments created for a specific shipper during the day and returns a manifest.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The unbounded list of objects to change with their values</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(List<global::Soenneker.Ups.OpenApiClient.Models.ApolloPatchReplaceReqV1_item> body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(List<global::Soenneker.Ups.OpenApiClient.Models.ApolloPatchReplaceReqV1_item> body, Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, "{+baseurl}/Forwarding/shipments?shipper_account_number={shipper_account_number}{&manifest_format*,pickup_date*,request_manifest*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Generate estimated freight rates based on the provided shipment and party details, and create the shipment.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Ups.OpenApiClient.Models.ApolloAirShipRequestV1 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/Forwarding/shipments", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentsRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Retrieves shipment details for air or ocean quotes based on the specified request parameters.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentsRequestBuilderGetQueryParameters 
        {
            /// <summary>The type of shipment (&quot;Air&quot; or &quot;Ocean&quot;).</summary>
            [Obsolete("This property is deprecated, use RequestTypeAsGetRequestTypeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("request_type")]
            public string? RequestType { get; set; }
#nullable restore
#else
            [QueryParameter("request_type")]
            public string RequestType { get; set; }
#endif
            /// <summary>The type of shipment (&quot;Air&quot; or &quot;Ocean&quot;).</summary>
            [QueryParameter("request_type")]
            public global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.GetRequest_typeQueryParameterType? RequestTypeAsGetRequestTypeQueryParameterType { get; set; }
            /// <summary>The unique identifier for the shipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipment_id")]
            public string? ShipmentId { get; set; }
#nullable restore
#else
            [QueryParameter("shipment_id")]
            public string ShipmentId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Processes all shipments created for a specific shipper during the day and returns a manifest.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentsRequestBuilderPatchQueryParameters 
        {
            /// <summary>The format of the manifest to be generated.</summary>
            [Obsolete("This property is deprecated, use ManifestFormatAsPatchManifestFormatQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("manifest_format")]
            public string? ManifestFormat { get; set; }
#nullable restore
#else
            [QueryParameter("manifest_format")]
            public string ManifestFormat { get; set; }
#endif
            /// <summary>The format of the manifest to be generated.</summary>
            [QueryParameter("manifest_format")]
            public global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.PatchManifest_formatQueryParameterType? ManifestFormatAsPatchManifestFormatQueryParameterType { get; set; }
            /// <summary>The &lt;a href=&quot;https://www.rfc-editor.org/rfc/rfc3339#section-5.6&quot; target=&quot;_blank&quot;&gt;RFC 3339&lt;/a&gt; scheduled pickup date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pickup_date")]
            public string? PickupDate { get; set; }
#nullable restore
#else
            [QueryParameter("pickup_date")]
            public string PickupDate { get; set; }
#endif
            /// <summary>The flag indicating whether a manifest should be generated.</summary>
            [QueryParameter("request_manifest")]
            public bool? RequestManifest { get; set; }
            /// <summary>Unique shipper number. Required for all updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_account_number")]
            public string? ShipperAccountNumber { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_account_number")]
            public string ShipperAccountNumber { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentsRequestBuilderPatchRequestConfiguration : RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Shipments.ShipmentsRequestBuilder.ShipmentsRequestBuilderPatchQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShipmentsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
