// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Ups.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes
{
    /// <summary>
    /// Builds and executes requests for operations under \Forwarding\info\service-types
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServiceTypesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServiceTypesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Forwarding/info/service-types?consignee_country_code={consignee_country_code}{&consignee_city*,consignee_postal_code*,consignee_state_code*,shipper_account_number*,shipper_city*,shipper_country_code*,shipper_postal_code*,shipper_state_code*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServiceTypesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Forwarding/info/service-types?consignee_country_code={consignee_country_code}{&consignee_city*,consignee_postal_code*,consignee_state_code*,shipper_account_number*,shipper_city*,shipper_country_code*,shipper_postal_code*,shipper_state_code*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves available service types based on shipper and consignee information.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Models.ServiceTypeSearchResponseV1"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ServiceTypeSearchResponseV1?> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder.ServiceTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Ups.OpenApiClient.Models.ServiceTypeSearchResponseV1> GetAsync(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder.ServiceTypesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Ups.OpenApiClient.Models.ApolloErrorResponseV1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Ups.OpenApiClient.Models.ServiceTypeSearchResponseV1>(requestInfo, global::Soenneker.Ups.OpenApiClient.Models.ServiceTypeSearchResponseV1.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves available service types based on shipper and consignee information.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder.ServiceTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder.ServiceTypesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves available service types based on shipper and consignee information.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ServiceTypesRequestBuilderGetQueryParameters 
        {
            /// <summary>Consignee city.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("consignee_city")]
            public string? ConsigneeCity { get; set; }
#nullable restore
#else
            [QueryParameter("consignee_city")]
            public string ConsigneeCity { get; set; }
#endif
            /// <summary>Consignee country code (2-letter ISO).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("consignee_country_code")]
            public string? ConsigneeCountryCode { get; set; }
#nullable restore
#else
            [QueryParameter("consignee_country_code")]
            public string ConsigneeCountryCode { get; set; }
#endif
            /// <summary>Consignee postal code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("consignee_postal_code")]
            public string? ConsigneePostalCode { get; set; }
#nullable restore
#else
            [QueryParameter("consignee_postal_code")]
            public string ConsigneePostalCode { get; set; }
#endif
            /// <summary>Consignee state code (2-letter code).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("consignee_state_code")]
            public string? ConsigneeStateCode { get; set; }
#nullable restore
#else
            [QueryParameter("consignee_state_code")]
            public string ConsigneeStateCode { get; set; }
#endif
            /// <summary>Shipper account number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_account_number")]
            public string? ShipperAccountNumber { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_account_number")]
            public string ShipperAccountNumber { get; set; }
#endif
            /// <summary>Shipper city.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_city")]
            public string? ShipperCity { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_city")]
            public string ShipperCity { get; set; }
#endif
            /// <summary>The shipper country code is required when the shipper account number is not provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_country_code")]
            public string? ShipperCountryCode { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_country_code")]
            public string ShipperCountryCode { get; set; }
#endif
            /// <summary>Shipper postal code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_postal_code")]
            public string? ShipperPostalCode { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_postal_code")]
            public string ShipperPostalCode { get; set; }
#endif
            /// <summary>Shipper state code (2-letter code).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shipper_state_code")]
            public string? ShipperStateCode { get; set; }
#nullable restore
#else
            [QueryParameter("shipper_state_code")]
            public string ShipperStateCode { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ServiceTypesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Ups.OpenApiClient.Forwarding.Info.ServiceTypes.ServiceTypesRequestBuilder.ServiceTypesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
